### ISSUE TITLE
haywire formatting?

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#106]
child of #117 

from @zippy 

https://chat.holochain.net/holo/pl/nfnckqdp6tgumn64we3fpxhzdo

Suspicion:  I feel like we have cargo fmt setups that fight against eachother because I keeps seeing commits (and I myself have made some) that introduce tons of changes that are just formatting.   

Desire: I would like to have this not happen.

Request: Can people please check-out commit: `c3b0f6a2c825686edc357c7254e851673111a47b` on develop  and run both:

`cargo fmt`

and

`cargo clean`
`cargo clippy`

To see if this introduces any changes to the code in your configuration.  Then we can diagnose the settings differences between us if it does.

Thanks. (edited)

**Comment by sphinxc0re** [comment]
This is most likely because of different rustfmt versions. If we all agree to only use the docker setup for this, it should be fine.

**Comment by thedavidmeister** [comment]
summary:

formatting and linting: pinned to a nightly version
test suite that MUST pass: unpinned stable
test suite that MAY fail (but runs on travis): unpinned nightly
wasm test suite MUST pass: unpinned nightly

**Comment by thedavidmeister** [comment]
@sphinxc0re @ddd-mtl @zippy is this resolved now?

i've been getting reliable fmt matching CI on my local when running `. docker/run-fmt`
