### ISSUE TITLE
During the step of networking tools installation, after entering the command 'npm run bootstrap', the terminal gets stuck

### ISSUE THREAD

**Issue by dhtnetwork** [holochain/holochain-rust#1063]
Hank - can you provide more details and attached the screenshot here? Thanks

**Comment by Connoropolous** [comment]
we no longer have this `npm run bootstrap` step

**Comment by Connoropolous** [comment]
Also, @dhtnetwork "Hank" never got tagged here, so not sure if they saw this or not?
