### ISSUE TITLE
Conductor should be able to start instance even if the chain does not contain DNA or agent entries

### ISSUE THREAD

**Issue by maackle** [holochain/holochain-rust#1095]
Seems that conductor assumes these two entries were successfully written and can't start the instance if the agent entry can't be found.

**Comment by lucksus** [comment]
Really? The conductor was actually initializaing the chain on every start-up until recently. I've added code last week that tries to load a chain and if that fails initializes a new one.. What makes you think that it can't start an instance without initialized chain?

**Comment by maackle** [comment]
I think this was due to the misleading error messages addressed in #1075
