### ISSUE TITLE
hc package 0.0.6 not displaying rust compiler error/warnings

### ISSUE THREAD

**Issue by jdeepee** [holochain/holochain-rust#1118]
I have recently moved from 0.0.3 -> 0.0.6. Previously when I would run `hc package` in my apps directory it would compile my rust code and show any errors/warnings that were thrown up by the compiler. This was really helpful for development, now when I run `hc package` it just shows `created dna package file at "path/to/dna.json"`. Is there a step I am missing in upgrading my application from 0.0.3 -> 0.0.6, or has there been some changes to hc package?

Rust is on the correct version and using hc 0.0.6 binary from release.

**Comment by AmrTarekMo** [comment]
make sure to update the dependencies in Cargo.toml file to v.0.0.6-alpha and recompile.

**Comment by jdeepee** [comment]
I didn't change my .build file -> .hcbuild. Once I renamed the build file it built the application correctly
