### ISSUE TITLE
Zome/Runtime hash mismatch issue persists

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#1135]
Even when I'm running 0.0.7-alpha in the HDK, and in the runtime I still get a warning:

```shell
$ hc --version
hc 0.0.7-alpha
```
Cargo.toml
```toml
  hdk = { git = "https://github.com/holochain/holochain-rust" , tag = "v0.0.7-alpha" }
```

```shell
$ hc test
...
WARNING! The git-hash of the runtime and the zome don't match.
Runtime hash: 974dc0deb34f30ba8120a553c69178af9bd37ed1
Zome hash: 3d3e280c21978ea823cd92ad98723c054f045815
...
```

**Comment by Connoropolous** [comment]
x this, it was running in the nodejs conductor, at a different version. Useful! Hehe

**Comment by pospi** [comment]
Ah, thanks for the above. I started getting this randomly in my repo and couldn't figure out why. Perhaps I need to update try-o-rama...

**Comment by pospi** [comment]
Nope! It was totally intermittent lol
