### ISSUE TITLE
CI MVP v1.0

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#117]
this is a ticket/epic to track our CI progress towards an MVP (basically, clearly helping more than hurting productivity)

the original motivation for this comes from a discussion between @zippy @sphinxc0re and myself and summarised here: https://github.com/holochain/holochain-rust/issues/106#issuecomment-403011101

each individual task should be tracked as a child ticket though

**Comment by Connoropolous** [comment]
#209 is related, just documenting
