### ISSUE TITLE
New ws rpc "call" method fails if inner params set to null

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#1191]
Using the new "call" method, if the inner params value is null, the call fails. If empty inner params are explicitly {} it works.

**Comment by Connoropolous** [comment]
that's no fun!

We have a PR (link above this comment) that hasn't yet addressed this, but is starting to integrate it as feedback, up now

**Comment by Connoropolous** [comment]
@willemolding you have something in progress related to this as well now I believe?

**Comment by dymayday** [comment]
Hi! This is fixed in https://github.com/holochain/holochain-rust/pull/1271 :)
