### ISSUE TITLE
Bus error when running `node test/index.js` (v0.0.8)

### ISSUE THREAD

**Issue by marcusnewton1** [holochain/holochain-rust#1195]
I'm using the dependency "@holochain/holochain-nodejs": "^0.4.7-alpha" in the test/ folder and node v11.11.0

**Comment by Connoropolous** [comment]
Hi marcus,

Can you share the details of the error you encountered here?

**Comment by maackle** [comment]
We are no longer using or supporting the NodeJS conductor for tests, so this is now outdated. We made the switch with https://github.com/holochain/holochain-rust/pull/1475
