### ISSUE TITLE
[FEEDBACK] Holochain/Holo Leadership

### ISSUE THREAD

**Issue by lazaridiscom** [holochain/holochain-rust#1230]
(writing this here in the heart of the project, instead of sending emails to "email-sinks")

This is not to open a discussion (at least i'll not go into discussions), but just to give you a "external opinion".

My evaluation result (use case A: gaming, use case b: large-scale distributed app) :

> # Holochain Starter
> 
> Apr. 2019
> 
> Exceptionally weak documentation, project-organization and leadership
> 
> Project is mainly focused on own use-case (Holo)
> 
> To early to adopt.

Why "weak leadership" ?

Because the leadership must ensure that the core-developers STAY AWAY from documentation, simply because they mess it up (and of course because they should invest their time in core-development).

When the developer with the most commits looses time revieving doc-revisions (of documentation which is quite messy and misleading), then something is very very wrong.

Fix it.

(personally I'll possibly take a look again in a few months)

**Comment by zippy** [comment]
Thanks for your feedback.  As it's clear from you that isn't up for discussion, I'm closing this issue and will move the feedback into other channels.
