### ISSUE TITLE
How to simulate network partitions with nodejs conductor?

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-rust#1236]
This may be a feature already provided by the modular nature of the test conductor, but if this is the case it would be really nice to have example documentation on how to simulate network partitions, similarly to the [existing example](https://developer.holochain.org/guide/latest/scenario_testing_setup.html#full-multiple-instances-example) on multiple instances.

I suppose what I'm asking about in terms of the example code linked is the existence of methods on `instance`s to detach / attach them to different `dna`s at runtime.

The use-case here is that I want to be able to test the behaviour of two simultaneous modifications to DHT links by two parties who are unaware of each other, and the way in which the network recovers from the conflict. Am I thinking about testing the right way?

**Comment by zippy** [comment]
This is a great use-case.  We've talked about it, but the current tooling doesn't actually let you do that explicitly.

**Comment by maackle** [comment]
Our networking isn't at the point where it makes sense to test the subtleties of network topology, but this would totally be a cool tool we'll need down the road, and one that I suspect can be built as a standalone, i.e. does not require any significant change (maybe no change at all) to holochain-core, it can just spin up a conductor and start adding and removing instances from it as the test progresses.

**Comment by maackle** [comment]
This is now planned as part of our testing strategy, to be integrated into testing tools like [diorama](https://github.com/holochain/diorama). It's not done but on the roadmap.
