### ISSUE TITLE
n3h_persistence_path missing needs better error message

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#1251]
When starting a conductor, if `n3h_persistence_path` is empty or not found, the error message is very not helpful

<img width="1284" alt="Screen Shot 2019-04-11 at 5 25 34 PM" src="https://user-images.githubusercontent.com/1409121/55994175-053d0d80-5c7f-11e9-9552-c2e4a1eca1fd.png">

**Comment by Connoropolous** [comment]
Actually, this suggests some kind of misrepresentation in the docs, which say that atttribute is optional

**Comment by Connoropolous** [comment]
https://developer.holochain.org/guide/0.0.9-alpha/conductor_networking.html#n3h_persistence_path-string-optional

**Comment by Connoropolous** [comment]
@ddd-mtl fyi there is this issue logged relating to some of the work you're now doing

**Comment by jamesray1** [comment]
@Connoropolous, here is a currently working doc link for the above:

https://github.com/holochain/holochain-rust/blob/master/doc/holochain_101/src/conductor_networking.md#L9

In your screenshot, while you probably noticed, note the N3H_LOG_LEVEL: i, which is info level. So it wouldn't cause the build to fail, i.e. be an error. It just means that if the path is not set, then n3h will not be able to store persisted data.

Does that make sense and address your concern?

**Comment by Connoropolous** [comment]
From my perspective, any n3h related issue can be closed now!

**Comment by jamesray1** [comment]
Oh OK. Sorry, I should've asked, does this issue still need to be kept open? Looks like lib3h is going to fully replace n3h, yes? I just had a look and it seems like n3h is still being used.

https://github.com/holochain/holochain-rust/search?p=2&q=n3h&unscoped_q=n3h

**Comment by jamesray1** [comment]
#https://github.com/holochain/n3h/pull/118
