### ISSUE TITLE
Move automated Docker hub build to "holochain/holochain-rust"

### ISSUE THREAD

**Issue by sphinxc0re** [holochain/holochain-rust#126]
Currently the image for developing and running CI tests is being built on Docker hub. Specifically:
`sphinxc0re/holochain-rust`
Soon, we should move this to
`holochain/holochain-rust`

**Comment by Connoropolous** [comment]
@sphinxc0re I suppose this is actually complete now?

**Comment by zippy** [comment]
Yes this got completed a while back.  Closing.
