### ISSUE TITLE
Holochain Instance Error: Network not initialized - hc test

### ISSUE THREAD

**Issue by jdeepee** [holochain/holochain-rust#1269]
Hi there, I am trying to run tests on my holochain application. But I receive the following error when running hc test.

`Reading DNA from /home/josh/Documents/junto/Junto/junto-rust/dist/junto-rust.dna.json
Failed to load instance josh from storage: ErrorGeneric("State could not be loaded due to NoneError")
Initializing new chain...
2019-04-15 19:09:08:josh: dna/initialize: Couldn't get DNA and agent from chain: ErrorGeneric("Agent entry not found")
2019-04-15 19:09:08:josh: dna/initialize: Initializing new chain from given DNA...
2019-04-15 19:09:09:josh: debug/initialize: created public token: HashString("QmZjmvEnMymW1opVY1yemwyzQbeuftp2WyM5yVqh8wZUT1")
not ok 1 Error: unable to start conductor: Error while trying to create instance "josh": Holochain Instance Error: "{\"kind\":{\"ErrorGeneric\":\"Network not initialized\"},\"file\":\"/home/travis/build/holochain/holochain-rust/core/src/nucleus/ribosome/runtime.rs\",\"line\":\"192\"}")`

My hc version is: 0.0.11-alpha1, holochain conductor version: 0.0.11-alpha1 and n3h version: 0.0.9-alpha2.

I have tried to use hc/holochain versions 0.0.9 in order to be in line with the n3h version but it didn't seem to change anything. 

Can anyone give me some information on what could be causing this problem? I thought it could be a problem with the way I have n3h configured, all I have done is cloned the repo and ran npm install - not sure if anything pointing to this repo should be in my path? 

Thanks

**Comment by Connoropolous** [comment]
Hi @jdeepee 
I think you have come across a version issue, that is a mistake in the release process. 
There should be a newer version of n3h and there isn't. If you simply cloned n3h, please try updating to the latest on the `master` branch and see if your issue is resolved?

**Comment by jdeepee** [comment]
Hi @Connoropolous thanks for the reply. I just ran `npm install` on the master branch but my issue still persists. Should I install globally with `npm install -g`?

**Comment by Connoropolous** [comment]
no, that's not necessary. So, to confirm, your `n3h` version is now up to date with the latest code on the `master` branch. You did a git pull?

**Comment by jdeepee** [comment]
Yes it is up to date with master. Do you know what specifically n3h is used for? Is it used by the conductor? Currently I don't see how the conductor can interface with the n3h package. Its currently just cloned in my downloads folder and then npm install ran inside, surely it would need to be installed globally or put in the same directory as my conductor/holochain app? Forgive me if I am wrong - don't have much experience with npm/node.

**Comment by zippy** [comment]
The network error looks suspect.  Why is the path `home /travis..`  It seems more like the problem here is with the missing DNA.  I'm guessing you might not have your DNA file in the right locations or it hasn't be built.  Did you do `hc package`?  and what does that output?

**Comment by jdeepee** [comment]
Hi @zippy. I used a full path to the dna.json file. Using a local path: `./dist/junto-rust.dna.json`still received the same error. I have packaged my application and everything compiles with no errors - just warnings. The output is: 
`Created DNA package file at "/home/josh/Documents/junto/Junto/junto-rust/dist/junto-rust.dna.json"
DNA hash: QmYHesPPjoZdWFHbmWXrWiatJsVqNQwGyYY4vFKxxjp64t`

I have also tried running tests on the same application on my mac on the latest versions of hc, holochain conductor and n3h. Same issue. Perhaps there is something wrong with my applications structure and zome(s) although to my eye it seems to be inline with the holochain guidebook. App code is here: https://github.com/juntofoundation/Junto

**Comment by jdeepee** [comment]
Updating to the latest hc & holochain version: 0.0.12-alpha1 and holochain-nodejs version: 0.4.11-alpha1 fixed the problem. Tests are now running and the Junto Holochain Application instantiated. Thanks for all your hard work on these releases!

**Comment by Connoropolous** [comment]
Good to hear @jdeepee !
