### ISSUE TITLE
CI failing: rust_sodium-sys compilation attempts getting back 404 errors

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#1315]
Eric says:
"It seems like this has been happening forever that the sodium download fail and kill the CI."

addressing the failing tests on the develop branch
https://travis-ci.com/holochain/holochain-rust/branches

lucksus
Seems it died during compilation?

connorturland
Ya. There's two builds that died to compare

connorturland
interestingly appveyor just failed with the same thing we saw over on circleci
```
"--- stderr
thread 'main' panicked at 'Download error: HTTP 404', C:\Users\master.cargo\registry\src\github.com-1ecc6299db9ec823\rust_sodium-sys-0.10.3\build.rs:81:9"
```

https://ci.appveyor.com/project/thedavidmeister/holochain-rust/builds/24047414/job/ygw3pk8jf18b3d7w
on a README changes only PR
who might have relevant context for why rust_sodium-sys compilation attempts might be getting back 404 errors? This is causing failures across multiple CI platforms

zippy
It seems like this has been happening foreve that the sodium download fail and kill the CI.  I wonder if we can add some retries into the script @thedavidmeister ?

lucksus
I wonder if we want to either
add that file to the repo, since we are checking its hash anyway
host it somewhere else on our own server
?

connorturland
interesting stuff. thanks for starting to flush this issue out. I don't have much of a perspective on the issue, just holding for its resolution  

ashantimutinta
I prefer we add the file to the repo because if someone ever wanted to work offline this would work better
Problem is that we would have to maintain versions

lucksus
Another drawback would be size of the repo, but I concur that the problem of not being able to get everything needed to build, especially in CI context, is worse.

ashantimutinta
hmmm there is also that we would need to maintain it over all the platforms we are supporting... Hmmm that might be a lot of work. Can we build from source?

**Comment by Connoropolous** [comment]
david
"I already put an upstream issue for this
If needed we can fork"

connor
well, from what I can tell, at the moment it is causing every build of develop to fail
so its gone from flaky to not working
I think

thedavidmeister
yes i heard, i'll also fix this
i'm going to try forking upstream and sticking a submodule for libsodium in
and skip the download in the build script, go straight into make

**Comment by thedavidmeister** [comment]
@Connoropolous 2 things:

- upstream totally broke on windows when libsodium stopped hosting the 16 version of the lib, so we're now using 17
- upstream added a fallback URL on s3 so if the first download fails it attempts that, which should make everything a lot more reliable overall
- we are pointing to a random commit from the fork, we should use the official upstream asap
