### ISSUE TITLE
Simplify install with `Brew install holochain` or `choco install holochain`

### ISSUE THREAD

**Issue by changalberto** [holochain/holochain-rust#1319]
Not sure if this is a duplicate, or if there are some technical barriers to this. But I personally think that having the ability to install the latest `hc cli` via package managers would simplify the process a lot.

**Comment by thedavidmeister** [comment]
@changalberto i've got this working in develop branch (about 5 mins ago) for mac/linux through the nix package manager

```shell
# install nix https://nixos.org/nix/download.html
curl https://nixos.org/nix/install | sh

# globally install holochain and hc
nix-env -f https://holochain.love/nightly -iA holochain hc

# globally upgrade holochain and hc (untested, watch this space)
nix-env -f https://holochain.love/nightly -uA holochain hc

# globally uninstall holochain and hc
nix-env -e holochain hc

# drop into a temporary shell containing all dependencies for development (rust etc.)
nix-shell https://holochain.love/nightly
```

once this hits master branch (next few days probably) then you can hit `https://holochain.love` without the `/nightly`

for windows... well the nix community is working on a port, but i think i'd like to see what can be done for `choco`

**Comment by changalberto** [comment]
@thedavidmeister Is there a way to target which version I want to install at the moment?

**Comment by thedavidmeister** [comment]
@changalberto not just yet with the above steps

you'll get the binary version that was live as at the commit of the repo

e.g. if you did something more like this:

```
cd path/to/holochain-rust
git checkout b89238971f9637156122db5ee47ed34cd6a7d938 && nix-shell --run 'hc -V'
# hc 0.0.14-alpha1
git checkout 1d36d11c4484f957a510eaa8a33cc5a4e8e3fed4 && nix-shell --run 'hc -V'
# hc 0.0.15-alpha1
```

this just tracks current master:

```
nix-shell https://holochain.love --run 'hc -V'
```

definitely planned to make this more ergonomic so that it can be set explicitly rather than juggling repo-level commits

this also works:

```
nix-shell https://github.com/holochain/holochain-rust/archive/1d36d11c4484f957a510eaa8a33cc5a4e8e3fed4.tar.gz --run 'hc -V'
```

pointing nix-shell straight at the tarball generated by github for whatever commit you want

**Comment by willemolding** [comment]
Using the nix-shell with http://holochain.love is live and seems to be a good solution to this on all platforms

**Comment by thedavidmeister** [comment]
@willemolding yes and there is also a `Vagrantfile` that wraps nix shell for any platforms that don't have native support (windows)
