### ISSUE TITLE
Capabilities MVP

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#133]

**Comment by zippy** [comment]
MVP of capabilities token associated with and checked by  the semantically named capability that groups exposed functions

**Comment by ddd-mtl** [comment]
- Public type = no token is required to use this Capability
- Zome = Need zome access token to  use this Capablity
- ApiKey = Need App access token to use the Capability
- Agent = Need access token of a particular Agent to use the Capability

**Comment by thedavidmeister** [comment]
the capabilities are all placeholdery and dumb in the zome api fns and callbacks

please review, there are TODOs going up in the validate PR over at #97

**Comment by jamesray1** [comment]
This seems to be outdated?
