### ISSUE TITLE
decide on format of arguments in DNA

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#134]
we could use either list of arguments by name/type pairs

or an object where the key is the name, and the type is value,

e.g. 

```json
          {
              "name": "newPost",
              "signature" :
              {
                  "inputs" : [
                      {
                          "name": "post",
                          "type": "string"
                      }
                  ],
                  "outputs" : [
                      {
                          "name": "hash",
                          "type": "string"
                      }
                  ]
              },
```

or 

```json
{
  "name": "newPost",
  "params" : {
    "post": "string",
  },
  "returns" : {
    "hash": "hash",
  },
}
```

**Comment by zippy** [comment]
What ever way we go, the way we do it for signals should match.

**Comment by neonphog** [comment]
### arrays of type / name pairs

pro: easier to deserialized into strongly typed structs

### compact `"name": "type"`

pro: much more human readable / writable

---

I guess I'd lean toward the more machine-oriented first option, as we're hoping to have fancy tools for generating / working with DNA in any case.

**Comment by zippy** [comment]
Ok, I'm going to recommend a middle ground where we remove the "signature" object (because it's unnecessary) but use the typed values as per @neonphog's leaning and @lucksus's from our call, hence:

```
          "functions": [
            {
              "name": "newPost",
              "inputs" : [
                  {
                      "name": "post",
                      "type": "string"
                  }
              ],
              "outputs" : [
                  {
                      "name": "hash",
                      "type": "string"
                  }
              ],
            },
            // ...
          ],
          "signals": [
            {
              "name": "Post",
              "description": "signal emmited when a post is committed",
              "config-params": null,
              "arguments": {
                  "name": "hash",
                  "type": "hash"
              },
            // ...
          ],
```

**Comment by zippy** [comment]
To complete this requires just minor changes to the `dna` crate

**Comment by lucksus** [comment]
Cool, so this is decided, and this ticket is actually done, right?

**Comment by zippy** [comment]
Yes, but I don't want to get the fact that this needs to be updated in the `dna` crate.  @lucksus It seems like you would need to update it there to get your example app crate actually working correctly right?  If not then there's dependency problem.
