### ISSUE TITLE
Invite to the chat of developers

### ISSUE THREAD

**Issue by GildedHonour** [holochain/holochain-rust#1345]
I sent a request to https://chat.holochain.org and there's been no reply at all.

**Comment by thedavidmeister** [comment]
@GildedHonour oh? it's an open chat server, who did you send a request to and for what?

**Comment by zippy** [comment]
@thedavidmeister currently the chat requires an invite because we were getting spammed, but we invite pretty much anybody who asks.  @GildedHonour did you get in yet?

**Comment by GildedHonour** [comment]
Yes

El 22 de mayo de 2019 10:43:01 GMT-03:00, Eric Harris-Braun <notifications@github.com> escribió:
>@thedavidmeister currently the chat requires an invite because we were
>getting spammed, but we invite pretty much anybody who asks. 
>@GildedHonour did you get in yet?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/holochain/holochain-rust/issues/1345#issuecomment-494808124

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
