### ISSUE TITLE
Implement thread-safe incubator/actor for T: HashTable

### ISSUE THREAD

**Issue by sphinxc0re** [holochain/holochain-rust#135]
Example:
```rust
#[derive(Clone)]
struct TableIncubator {
    sender: Sender<IncubatorMsg>
}

impl TableIncubator {
    pub fn new<T: HashTable>(table: T) { ... } // spawn a thread with a listener
}

impl HashTable for TableIncubator { ... } // make this look like a hash table for convenience
```

**Comment by zippy** [comment]
We need to think about how this will generalize and we can use this pattern for the networking abstraction #99, so that the threading model is written once and used by all of our trait pattern implementations.

**Comment by thedavidmeister** [comment]
as per discussions last night, "incubator" sounds a lot like "actor" ;)

in which case, https://github.com/actix/actix might generalize everything nicely without us needing to write our own implementation

**Comment by sphinxc0re** [comment]
@thedavidmeister or maybe https://github.com/riker-rs/riker/ which looks even more promising

**Comment by thedavidmeister** [comment]
also https://github.com/aeickhoff/kay

**Comment by thedavidmeister** [comment]
got a spike for riker going, updates here:

pros:

- looks like we can almost completely flush out generic types and replace with message protocol enums
- putting actor refs in the state tree works pretty much as you'd hope
- looks like extending chain and hash table to work as actors is a relatively minor refactor
- comes with persistence built in, so state history and rebuilding are out of the box
- docs are more comprehensive than actix
- comes with futures for pulling data back out of an actor after sending a message

cons:

- needs nightly to make futures work
- config is a bit clunky

other:
