### ISSUE TITLE
JSON calls returning "signal" before "result"

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#1397]
Here is an example of a JSON request sent from my client to the hc backend:

{"jsonrpc":"2.0","id":"GetPostsBy+","method":"call","params":{"instance_id":"test-instance","zome":"coolcats","function":"get_posts_by","args":{"handles":[""]}}}

Here is an example of what I am getting back from the hc backend:

`{"signal":{"signal_type":"Internal","action":{"action_type":"ReturnZomeFunctionResult","data":{"call":{"id":{"prefix":8,"offset":151},"zome_name":"coolcats","cap":{"cap_token":"QmTN4G8abpd2vKNg1TndPoSWocyuM9TqY4JSmFqeQvuB7p","provenance":["HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma","VNXRZie6ueGhaYel2eapL1pw0Nh6VwbBGV1oiAWvUDJD4gUM0dUj8ir5ibv7cluuwFgHfIwUEH+LOnbPhuqlBA=="]},"fn_name":"get_posts_by","parameters":"{\"handles\":[\"\"]}"},"result":{"Ok":"{\"value\":[]}"}}},"id":{"prefix":101,"offset":2}},"instance_id":"test-instance"}`

**Comment by pythagorean** [comment]
Note I can parse this `"signal"` to extract the result entry but the `"id"` field is lost and replaced by `{"prefix":8,"offset":151}` which I cannot then match to the redux method I need.

**Comment by pythagorean** [comment]
Ok if I ignore and throw away the "signal" response, I do receive the "result" in a second response, this seems to be the way to handle it for now.

**Comment by maackle** [comment]
This is a symptom of https://github.com/holochain/holochain-rust/issues/1364, we need to have a way to selectively turn off these Internal signals. But in general, once Signals land as a feature, your client will have to handle "signal" messages that can come any time.

**Comment by pythagorean** [comment]
Well the good news is I have already put code to receive and discard so it's no big deal to know where to put the handler. :)

Should be documented though, it confused me for a while to figure out what to do with these.

**Comment by pdaoust** [comment]
Thanks for the recommendation @pythagorean ; I'll remember that when I tackle the articles on RPC interface and signals.

**Comment by maackle** [comment]
I think the main gist of this issue is that the Trace signals were leaking out, but now that should be tightened up with https://github.com/holochain/holochain-rust/pull/1428 et al
