### ISSUE TITLE
Adding bridges through admin interface is impossible

### ISSUE THREAD

**Issue by maackle** [holochain/holochain-rust#1419]
While we can add instances and bridges through admin interface methods, the integrity checks and order of operations for instance instantiation makes it impossible in practice to actually get things hooked up properly.

* As soon as `admin/instance/add` is called, the instance gets instantiated. This process also checks for bridges, and adds the bridge handles as instance identifiers.
    * If `admin/bridge/add` is called after `admin/instance/add`, the bridge handle is not registered as an instance identifier, and bridge calls fail
    * If bridges are added before the instances, not only does the integrity check fail, but the bridge dependency resolver doesn't know what to do since it can't find the instances the bridge is referring to, as soon as the first instance is added

There are several ways we could fix this, and I'm not sure which is best.

- we could have an admin function that sets up multiple instances and bridges atomically, to avoid invalid intermediate states
- we could rework instance creation, so the instance is not fully instantiated until it `start`s
- we could disable integrity checks when using admin interface methods
- and many more...

**Comment by lucksus** [comment]
I think what would help here is respawning the caller instance so that its conductor_api delegate gets recreated with the new bridge handle. Looking into this now...
