### ISSUE TITLE
'hc run' has no option to use specific package name

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#1423]
Since I am using a directory structure with zome code under dna-src, I wanted to make my package name unique, using the `hc package -o <output>` syntax. However there is then no way for `hc run` to find this package unless I create a symlink to dna-src.dna.json as there is no option to specify the name.

**Comment by zippy** [comment]
Hey there @pythagorean this is a great catch, we should have an `hc run -i <input>` flag to match

**Comment by pythagorean** [comment]
Thanks. I just came here to close this if you hadn't already. :)
