### ISSUE TITLE
review whether multiple PairMeta returned from get_pair_meta should be sorted

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#144]
the choice to sort the PairMeta associated with a Pair from a HashTable was pretty arbitrary

the idea is that when meta has txn info on it as per #138 then we'll probably want to be able to order against that, but the exact algo hasn't been decided

**Comment by jamesray1** [comment]
This is outdated, I had a quick look but I can't tell if this is unresolved or not?

**Comment by thedavidmeister** [comment]
yeah, we have an index on EAVI to handle ordering
