### ISSUE TITLE
Scenario test hangs on `hdk::query_result`

### ISSUE THREAD

**Issue by maackle** [holochain/holochain-rust#1455]
Originally discovered by @pjkundert 

Running `hdk::query_result` immediately after `hdk::commit` in a zome function causes a scenario test to hang.

Adding `hdk::sleep(1)` immediately before the `hdk::query_result` causes the following error:

 ```
thread '<unnamed>' panicked at 'memory should be writable: Memory("trying to access region [5395..6460535] in memory [0..2031584]")', src/libcore/result.rs:997:5
```

**TODO** reproduce with minimal test case

**Comment by pjkundert** [comment]
I'm working on this; actually, I've noticed a quite a few issues with the hdk::send/receive handling in app_spec, so I'm bringing this all up-to-date at the same time as testing this issue...

**Comment by pjkundert** [comment]
Well, my app_spec test in the `feature-app-spec-query` branch did *not* exhibit this failure of hdk::query to reflect the previous hdk::commit_entry of a Post.   The failure persists in the HoloFuel test suite...
