### ISSUE TITLE
Windows Conductor fails to setup n3h

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#1460]
which blocks an important demo application.

After trying to run `./holochain.exe -c ./conductor-config.toml` on windows we get this:
(in https://github.com/Connoropolous/ready-chat-mac-electron)

```
 11:59:58.700 > Using config path: ./conductor-config.toml

11:59:58.709 > Unlocking agent keys:
Unlocking key for agent 'test_agent1':
Reading keystore from ./keystore.key

12:00:07.504 > Spawning network with working directory: ./n3hfolder

12:00:07.508 > response: Err(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })

12:00:07.511 > response: Err(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })

12:00:18.252 > Error while spawning network process: ErrorMessage { msg: "Err(ErrorMessage { msg: \"n3h version mismatch, expected: v0.0.13-alpha, got: None\" })" }

12:00:18.257 > Reading DNA from dna/holochain-basic-chat.dna.json

12:00:18.341 > thread '<unnamed>' panicked at 'Failure while attempting to create network worker with provided P2pConfig. Error: ErrorMessage { msg: "config.spawn or config.ipcUri is required" }', net\src\connection\net_connection_thread.rs:52:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

12:00:18.345 > thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Failed to obtain a connection to a p2p network module w/ config: {\"backend_kind\":\"IPC\",\"backend_config\":{\"socketType\":\"ws\",\"blockConnect\":false,\"bootstrapNodes\":[],\"ipcUri\":null},\"maybe_end_user_config\":{\"webproxy\":{\"connection\":{\"rsaBits\":1024,\"bind\":[\"wss://0.0.0.0:0/\"]},\"wssAdvertise\":\"auto\",\"wssRelayPeers\":null}}}: Failed to receive endpoint address from net worker: receiving on a closed channel" }', src\libcore\result.rs:997:5
```

**Comment by Connoropolous** [comment]
The true error here is

```
Error while spawning network process: ErrorMessage { msg: "Err(ErrorMessage { msg: \"n3h version mismatch, expected: v0.0.13-alpha, got: None\" })" }
```

This comes from: 
https://github.com/holochain/holochain-rust/blob/2f7f76273e653c46828a12eff64776b30ab9c0f7/net/src/ipc/n3h.rs#L163-L168

There is a binary: 
https://github.com/holochain/holochain-rust/blob/develop/net/src/ipc/n3h_pin.json#L66-L73
and it exists:
https://github.com/holochain/n3h/releases/tag/v0.0.13-alpha

so why does it fail?

**Comment by marcusnewton1** [comment]
n3h is supposed to be automatically downloaded by Holochain...when exactly does this occur?

**Comment by marcusnewton1** [comment]
Still same problem after running the downloadable n3h executable. The binary is showing up in `Users\[username_here]\AppData\Roaming\holochain\holochain\data\n3h-binaries\v0.0.13-alpha`

**Comment by mrbianchi** [comment]
Same error

**Comment by Connoropolous** [comment]
Hi @marcusnewton1 and @mrbianchi 
We are going to be looking into this error this week. It seems to affect Windows only. 

Please stand by. We'll update here with findings!

**Comment by Connoropolous** [comment]
@AshantiMutinta and I have traced that this seems to be an issue with nodejs/electron not outputting console.log lines on Windows, without special configuration

https://github.com/atom/atom/pull/9268

@AshantiMutinta I think we should try it with a `--enable-logging` flag passed
