### ISSUE TITLE
Starting two Conductors on same system fails to network between instances

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#1478]
Receiving error message:

`(@realmode@) [e] (ScIi).connect (wss://10.0.0.62:53318/?a=HcScIi9N8apdUo7giik383U8qA97Rfm6EMa3BHVzPwzborrw8qmuj9mdQqxwc3i) failed Error: Cannot connect to a peer with the same peerAddress: HcScIi9N8apdUo7giik383U8qA97Rfm6EMa3BHVzPwzborrw8qmuj9mdQqxwc3i`

First Conductor is started with:

```
[network]
n3h_persistence_path = "/tmp"
bootstrap_nodes = []
```

Once it has loaded and the p2p address has been obtained, the second Conductor was started in this case with:

```
[network]
n3h_persistence_path = "/tmp"
bootstrap_nodes = ["wss://10.0.0.62:53309/?a=HcScIi9N8apdUo7giik383U8qA97Rfm6EMa3BHVzPwzborrw8qmuj9mdQqxwc3i"]
```

**Comment by Connoropolous** [comment]
Hey @pythagorean 
we are aware that this is showing up not just for you, but universally. However, I believe that it still succeeds in connecting with other peers, independent of the appearance of this error message.

Did you observe a failure to connect between the two peers? I think that log may be a non-issue

**Comment by pythagorean** [comment]
Yes I observe a failure to connect between the peers. When I was able to run the Conductor previously (it's not been working for a few versions now) the two peers could see one another to Follow from my UI, now they do not.

**Comment by Connoropolous** [comment]
I see. 

Since you are running them both on one device, you can try using the non-bootstrap mode to make peer discovery work. It uses a service that's new in there called "MDNS" and it let's peers discover one another, if they're on a local network. 
Can you try with that? Just leave the `bootstrap_nodes` array empty/

**Comment by pythagorean** [comment]
I removed the `bootstrap_nodes` entry in the second Conductor config, they seem to have discovered one another but I get the same error and no connectivity between peers.

`(@realmode@) [e] (ScIi).connect (wss://10.0.0.62:49642/?a=HcScIi9N8apdUo7giik383U8qA97Rfm6EMa3BHVzPwzborrw8qmuj9mdQqxwc3i) failed Error: Cannot connect to a peer with the same peerAddress: HcScIi9N8apdUo7giik383U8qA97Rfm6EMa3BHVzPwzborrw8qmuj9mdQqxwc3i`

**Comment by Connoropolous** [comment]
do you know why it's binding to '10.0.0.62' ... do you have it configured specifically to do that?

**Comment by pythagorean** [comment]
No idea, and no I am not doing anything to configure that. I am on a WiFi network which assigns my system an IP.

**Comment by Connoropolous** [comment]
Oh. Just thought of something... please try adjusting `n3h_persistence_path`
Set the value to an empty directory, and a different one for both Conductor Configs... then run it :)

**Comment by pythagorean** [comment]
That fixes it, thanks.

**Comment by Connoropolous** [comment]
Fantastic.
