### ISSUE TITLE
Enable configuration UI Interface to listen outside of localhost on config.toml

### ISSUE THREAD

**Issue by mrbianchi** [holochain/holochain-rust#1480]
I'm running a hApp in the VM with Ubuntu.
My host OS is Windows.
I'm trying to access to the served UI Interface with Windows (http://192.168.0.40:3000/) but the connection is refused. 
I think that the UI Interface isn't listening outside the localhost (only access via VM)
I can't find parameter that let me configure the listening range (https://developer.holochain.org/guide/latest/conductor_ui_interfaces.html)

**Comment by pdaoust** [comment]
That's by design, because it's risky to open up your agency to the whole world. If this is something you want to be able to do yourself, you could set up a reverse proxy on the Ubuntu VM -- Nginx and HAProxy are both great. If I could make a recommendation, Nginx is way easier to configure.
