### ISSUE TITLE
create web access to api docs

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#15]
child of #117 

As an container developer and as a core developer, I want web access to rust library documentation, so as to be able to understand and navigate the codebase easily.

`cargo doc` builds all the docs and puts them into the `target` directory which is (rightfully) ignored in `.gitignore`

- [ ] setup github pages on this repo (or other solution) to serve the api docs.
- [ ] create a build script for release (maybe in travis) that deploys the docs build

**Comment by thedavidmeister** [comment]
@zippy IIRC, any lib that is pushed to crates.io automatically gets docs built and available at https://docs.rs/

in that case, #18 could kill two birds with one stone :)

**Comment by thedavidmeister** [comment]
alternatively there is a section in this tutorial explaining gh pages support - https://medium.com/@Razican/continuous-integration-and-code-coverage-report-for-a-rust-project-5dfd4d68fbe5

**Comment by Connoropolous** [comment]
Unless we choose to change this around, the github pages for holochain-rust repo is now occupied by the MDBOOK build... so we may have to create a different repo and do the build scripts to that repo to use github pages to host the API docs

**Comment by Connoropolous** [comment]
As discussed in other places, the alternative to this issue is to start shipping holochain-rust into crates.io, which would generate and host the API docs out-of-the-box. Seems like a big win.

How soon (if approved) can we do this? Starting to see how those docs look like, and start to polish them seems very important and generative

**Comment by thedavidmeister** [comment]
@Connoropolous i am for pushing to crates.io ASAP. handle expectations of maturity through versioning/comms, not avoiding publishing. Everything is public on github now.

but...

@zippy @sphinxc0re @AshantiMutinta @lucksus @ddd-mtl need to input into this decision.

if it's not controversial, let's 🚢 

if someone wants to wait, then we'll need to plan that wait... ADR? trello?

**Comment by Connoropolous** [comment]
Great to hear @thedavidmeister, I am curious to hear others thoughts

**Comment by AshantiMutinta** [comment]
You can go no wrong with crates.io, if that is everyone's first choice for obtaining packages, I would say why not. We should definitely pursue it

**Comment by jamesray1** [comment]
Can this be closed?

https://crates.io/search?q=holochain

https://developer.holochain.org/docs/api/

**Comment by thedavidmeister** [comment]
ooooh yes!

check this out https://docs.rs/crate/holochain/0.0.38-alpha13

that's awesome :D
