### ISSUE TITLE
Cannot have other attributes on function annotated with #[zome_fn(...)]

### ISSUE THREAD

**Issue by MightyAlex200** [holochain/holochain-rust#1619]
As the comment on [this line](https://github.com/holochain/holochain-rust/blob/release-0.0.25-alpha1/hdk-proc-macros/src/into_zome.rs#L211) mentions, when using the hdk proc-macro, if a function is annotated with `#[zome_fn(...)]`, it cannot be annotated with any other attributes without causing a compile error. This is a problem for me because I have a codebase where many of the functions have documentation comments, which count as attributes too, so I cannot update to the hdk proc-macro.

**Comment by willemolding** [comment]
Great catch. I'll take a look into this soon. Can you please post an example of a function that won't compile?

**Comment by MightyAlex200** [comment]
Yeah, here's a simple function that won't compile:

```rust
/// This comment will cause a compile error
#[zome_fn("hc_public")]
fn create_my_entry(entry: MyEntry) -> ZomeApiResult<Address> {
    let entry = Entry::App("my_entry".into(), entry.into());
    let address = hdk::commit_entry(&entry)?;
    Ok(address)
}
```
(in default zome created by `hc generate zomes/my_zome rust-proc`)

I recall not being able to use regular comments, either, but now I can only get documentation comments to stop compilation for some reason.

**Comment by willemolding** [comment]
This makes sense. Triple slash comments are treated the same was as `#[annotations]` so we just need to make sure the other annotations are carried across when the macro rewrites the function.
