### ISSUE TITLE
error: failed to load source for a dependency on `hdk`

### ISSUE THREAD

**Issue by elegant651** [holochain/holochain-rust#1633]
`[nix-shell:~/Desktop/epitodev/holochain/test_first_app]$ hc package
> cargo build --release --target=wasm32-unknown-unknown --target-dir=/Users/willpark/nix-holochain/lists/target
    Updating git repository `https://github.com/holochain/holochain-rust`
error: failed to load source for a dependency on `hdk`

Caused by:
  Unable to update https://github.com/holochain/holochain-rust?tag=0.0.25-alpha2

Caused by:
  failed to find tag `0.0.25-alpha2`

Caused by:
  reference 'refs/tags/0.0.25-alpha2' not found; class=Reference (4); code=NotFound (-3)
Error: command cargo build --release --target=wasm32-unknown-unknown --target-dir=/Users/willpark/nix-holochain/lists/target was not successful`

How can I resolve it?

**Comment by qubist** [comment]
I have this issue as well in `0.0.26-alpha1`! Output:

```
[nix-shell:~/me/hc-ur]$ hc test
Packaging files for testing to file: "/Users/me/hc-ur/dist/hc-ur.dna.json"
> cargo build --release --target=wasm32-unknown-unknown --target-dir=target
    Updating git repository `https://github.com/holochain/holochain-rust`
error: failed to load source for a dependency on `hdk`

Caused by:
  Unable to update https://github.com/holochain/holochain-rust?tag=0.0.26-alpha1

Caused by:
  failed to fetch into /Users/me/.cargo/git/db/holochain-rust-c3b6365fc5bfa642

Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded

Caused by:
  no authentication available
Error: command cargo build --release --target=wasm32-unknown-unknown --target-dir=target was not successful
```

**Comment by qubist** [comment]
Fiddling with my ssh-agent fixed mine I think

**Comment by elegant651** [comment]
just the issue occurred by wrong tag. should change 0.0.26-alpha1. it works.
