### ISSUE TITLE
holochain.love / multiversion installation

### ISSUE THREAD

**Issue by pegaltier** [holochain/holochain-rust#1649]
Multiversion installation, it can be possible like with NPM to execute the command line with the targeted version at the end of the URL ( nix-shell https://holochain.love@0.0.25 )

without any target it will install the latest one.

**Comment by willemolding** [comment]
This is possible currently using 
```
nix-shell https://github.com/holochain/holonix/tarball/<branch/tag/commit>
```
e.g.
```
nix-shell https://github.com/holochain/holonix/tarball/0.0.28
```

Note that these are holonix version tags and not holochain versions. Check out the [holonix repo](https://github.com/holochain/holonix) changelog to see the version mappings

**Comment by thedavidmeister** [comment]
pinning is documented https://docs.holochain.love/docs/configure/
