### ISSUE TITLE
Bad links in ValidatingLinkDefinition doc

### ISSUE THREAD

**Issue by qubist** [holochain/holochain-rust#1666]
The links `link!` `to!` and `from!` on the [ValidatingLinkDefinition documentation page](https://developer.holochain.org/api/latest/hdk/entry_definition/struct.ValidatingLinkDefinition.html) are broken and lead to 404 pages.

[This code](https://github.com/holochain/holochain-rust/blob/ea6161333bb34bec4176be67b4a7f9041c0535fe/hdk-rust/src/entry_definition.rs#L51) generates those links. The links should (I think) lead to `https://developer.holochain.org/api/latest/hdk/macro.[link/to/from].html` but instead they lead to `https://developer.holochain.org/api/latest/hdk/entry_definition/macro.[link/to/from].html`.

**Comment by qubist** [comment]
@freesig

**Comment by freesig** [comment]
I think these are missing a (../macro.link.html) etc.
I'll do a PR

**Comment by freesig** [comment]
It seems a lot of links are broken in the API right now but they have been the same for over 9 months so I think someone would have noticed before now. Most are setup like `[link!](macro.link.html)`. I can fix it by changing to `[link!](../macro.link.html)` but I'm wondering if something has changed recently in the build process to make the first style not work.
Apparently we should be able to use [intra-links](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md) but I can't get this to work at all in our toolchain.

**Comment by freesig** [comment]
I'm getting super weird behavior with intra links:
This works except you can see the reference link:
```
/// Some docs [define_zome macro][`define_zome`]
/// [`define_zome`]: hdk::define_zome
struct SomeType
```
This doesn't work
```
/// Some docs [define_zome macro][`define_zome`]
///
/// [`define_zome`]: hdk::define_zome
struct SomeType
```

There's a few options here that I can see:
1. Make all paths relative and which works but is fragile.
2. Figure out how to get intra-links working. It just uses rust paths so should be easier to maintain.
3. I'm curious how `[link!](macro.link.html)` must have worked before (Unless no-one notice for 9 months?)
