### ISSUE TITLE
documentation out of date (guide) - todo list example 0.028 alpha

### ISSUE THREAD

**Issue by nphias** [holochain/holochain-rust#1681]
when substituting the boiler plate zome code (lib.rs) with the todo example code (latest version) following error comes back:
```
error[E0463]: can't find crate for 'holochain_persistence_derive'
 --> src/lib.rs:6:1
  |
6 | extern crate holochain_persistence_derive;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `exchange`.

To learn more, run the command again with --verbose.
Error: command cargo build --release --target=wasm32-unknown-unknown --target-dir=target was not successful
```

**Comment by nphias** [comment]
fixed by pull request:
https://github.com/holochain/holochain-rust/pull/1700

will close when pull request is merged

**Comment by jamesray1** [comment]
[M3-docs]

Please note:

> We are currently revamping our developer documentation and have plans for a new guidebook. Please feel free to use the current guidebook, but note that it will be replaced in the future. 

https://developer.holochain.org/docs/guide/welcome/
