### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holochain-rust#17]

**Comment by thedavidmeister** [comment]
Here's a working example based on `rustup` that i put together while working on #19 

There is a PR up with docker-y things in it too, but looks like it uses `apt-get` to install `cargo` - not sure how that works with rustup?

```
FROM ubuntu

WORKDIR /root

RUN apt-get update && apt-get install libssl-dev pkg-config cmake zlib1g-dev curl -y

RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y

ENV PATH /root/.cargo/bin:$PATH

RUN rustc --version

COPY . /root/holochain

WORKDIR /root/holochain

RUN RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin

CMD cargo +nightly tarpaulin --all
```

**Comment by thedavidmeister** [comment]
@philipbeadle yo, there are several docker images merged in now, but they probably don't do quite what you want just yet

if you've got specific needs for images, let's chase up some followup tx
