### ISSUE TITLE
Compilation fails on nightlies since 2019-7-30 due to old await syntax

### ISSUE THREAD

**Issue by timotree3** [holochain/holochain-rust#1723]
https://github.com/rust-lang/rust/pull/62293 removed support for the `await!` syntax that we're currently using. The new `.await` syntax has worked since nightly-2019-05-08. It seems like it'd be safe to update the syntax we use.

**Comment by timotree3** [comment]
I'm working on a PR to update our uses now.

**Comment by thedavidmeister** [comment]
@timotree3 you need to use holonix, which contains the exact rust versions that are compatible with all relevant crates https://github.com/holochain/holonix

**Comment by timotree3** [comment]
Personally, I can't use the nix install option because I don't have the disk space. I'm not too worried about closing this because #1726 will fix it soon. :-) On a procedural note though, it doesn't actually seem to me like this issue has been resolved.

**Comment by thedavidmeister** [comment]
@timotree3 ok, is the refactor going to be compatible with the rust shipped in holonix?

**Comment by timotree3** [comment]
Yep. (Correct me if I'm wrong) but I believe Holonix uses 2019-07-14. The new syntax has been supported since 2019-05-08

**Comment by thedavidmeister** [comment]
@timotree3 ok sweet, well carry on then :)
