### ISSUE TITLE
README for app_spec doesn't list all dependencies

### ISSUE THREAD

**Issue by timotree3** [holochain/holochain-rust#1729]
I was trying to run the app spec tests, but I got an error:

```none
Error: Couldn't traverse DNA in directory "/home/timo/dev/holochain-rust/app_spec": No such file or directory (os error 2)
```

Eventually I figured out that the file or directory it was referring to was `wasm-gc`. Ignoring the unhelpful error message, this was something that I needed to install that wasn't listed in the [README.md][].

After I installed that one with cargo, I got the same error, but this time I figured out that it was about `wasm-opt`. This one is not so easy to install because it's not a rust crate. I believe if I did install this one I would've gotten the same error for `wasm2wat` and `wat2wasm`.

Is there some `make` sub-command that installs those Wasm-management tools? We could update the README to refer to it instead.

[README.md]: https://github.com/holochain/holochain-rust/blob/608f1ee8eb4af34fed9e8a2f1609ab3cba1f5925/app_spec/README.md

**Comment by thedavidmeister** [comment]
@timotree3 `wasm-gc` and `wasm-opt` are installed by holonix - https://docs.holochain.love
