### ISSUE TITLE
publish crates to crates.io

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#1730]
currently `hc` points at github to pull down e.g. the HDK etc.

this is because there is nothing published to crates.io

this means that build times are very slow because we need to pull down the full github repo every time after a flush or cache expirty just to to get one commit of one or two crates (e.g. for zome dev)

CC: @freesig @zippy @philipbeadle @willemolding

**Comment by willemolding** [comment]
This is done!
