### ISSUE TITLE
Where to ask about architecture?

### ISSUE THREAD

**Issue by dumblob** [holochain/holochain-rust#1820]
I couldn't find a good place to ask about the Holochain specification. The whitepaper is getting dusty (and is incomplete), the Go implementation is not maintained, the Rust implementation is still not on par with the Go implementation. And there seem to be no place for discussion and clarifying questions about Holochain architecture (a technical specification one would say).

1. My first question would be how to handle largely widespread Holochain application, which will store the more data the more participants there will be (typically social networks, chats, etc. - each newly coming participant in the network will produce a lot of data over maybe 20-40 years while the others will be "incentivized" to produce even more data due to the presence of the newcomer).
In the normal world around, the more the matter "lives" (imagine stone versus animal/human brain), the more & quicker it "forgets". How about pruning of "old" data instead of treating them exactly the same as new data (i.e. storing them next to the new data in the same high-speed storage which will get full really soon - way earlier than the anticipated duration of one account activity - i.e. way earlier than the 20-40 years on average). Currently it seems Holochain is boasting about ecological advantages over certain other networks, but is completely silent about having this ever-increasing (additive) nature without any opt-out mechanism (and no, starting a new chain is by far not a solution).

**Comment by thor-em** [comment]
[Holochain Forum](https://forum.holochain.org) is the best place for questions such as this :+1:

**Comment by willemolding** [comment]
@dumblob Hopefully you found the [concepts/architecture](https://forum.holochain.org/c/technical/holochain-concepts-architecture) channel in the forum. Look forward to hearing your questions there
