### ISSUE TITLE
"Visual Studio Code is unable to watch for file changes in this large workspace" (error ENOSPC)

### ISSUE THREAD

**Issue by jamesray1** [holochain/holochain-rust#1825]
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

Is anyone getting this error when working with Visual Studio code with this repo?

I am on Manjaro and am still getting the error after running `echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system`.

**Comment by willemolding** [comment]
This seems like a VSCode issue rather than a holochain issue right?

**Comment by jamesray1** [comment]
Yeah, and also it's related to using (Manjaro) Archlinux.
