### ISSUE TITLE
Latest git versions are not available on crates.io

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-rust#1844]
Looks like the publish scripts are missing steps that are being done manually?

With moving to a production bundled app, we're starting to require confidence that packages present in one location are available in every other expected location as well (;

**Comment by zippy** [comment]
Hey there @pospi I'm pretty sure this is working now, can you confirm from your end that it looks good?

**Comment by pospi** [comment]
Looks good! Or at least, the latest tag in here is on there as well (;
