### ISSUE TITLE
System Entry Types

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#186]
we need a system entry type abstraction/enum to hold system entry types:

- [ ] dna
- [ ] agent identity
- [ ] link
- [ ] key (non directly stored as pair)
- [ ] header (maybe as separate ticket)
- [ ] Migrate?
- [ ] Deletion?

**Comment by ddd-mtl** [comment]
Proposed implementation:
Add a `system_type` member  to `Pair` which is an enum of the above listed types.
A 'normal' entry's type would be `data` or `app_data`
Change Pair's `entry` member to an enum with variants depending on `system_type`
`Pair.header` might also be an enum variant.
Current `Entry` would be renamed to `DataEntry`
A `Headers` system type would not have any entry for example.

Would that work @thedavidmeister @zippy @lucksus ?

**Comment by ddd-mtl** [comment]
I find the word `Pair` lacking a bit of context. I'm not sur I grasp the mental modal behind this.

**Comment by ddd-mtl** [comment]
Maybe its better to change `Pair` to a trait have system types be implementation of the trait. I'll experiment.

**Comment by ddd-mtl** [comment]
Since we are using a `Chain`as metaphore, maybe `Pair` should be renamed `Link` or `Ring` to go with that metaphore?

**Comment by ddd-mtl** [comment]
I'm trying out a SysEntry Trait and have Dna implement it.

**Comment by thedavidmeister** [comment]
@ddd-mtl "pair" just means "a header and entry pair", there's no magic to the name :)

**Comment by ddd-mtl** [comment]
@thedavidmeister Oops I wasn't clear about `Pair`. My question was more about what  the 'Pair' struct is for, not about the 'Pair' name itself.
Becuase looking at the current state of the code seperating Entry from Header doesn't make any sense since the Entry's hash is never used as key. But I guess it is because in the Entry we only push the Entry and not the Pair.

**Comment by thedavidmeister** [comment]
@ddd-mtl @lucksus makes sense re: pair

i opened this https://github.com/holochain/holochain-rust/issues/243

**Comment by ddd-mtl** [comment]
Since system entries are also `Entry` I think we should rename non-system entries `AppEntry`
