### ISSUE TITLE
get_entry times out if no entry.

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holochain-rust#1882]
hey team, when I do the following which I thought would return a "none" 
```
pub(crate) fn handle_get_anchor(_anchor_address: Address) -> ZomeApiResult<Option<Entry>> {
    let root_anchor_entry = Entry::App(
        ROOT_ANCHOR_ENTRY.into(),
        RootAnchor {anchor_type: "root_anchor".into()}.into()
    );
    let root_anchor_entry_address = root_anchor_entry.address();
    hdk::get_entry(&root_anchor_entry_address)

    // hdk::get_entry(&anchor_address)
}
```
I keep getting this error
```
06:19:39 [try-o-rama] debug: restarted timer
06:19:39 [try-o-rama] debug: restarted timer
06:19:39 [try-o-rama] debug: restarted timer
06:20:24 [try-o-rama: try-o-rama conductor combined] warn: Zome call 'anchors/get_anchor' has been running for more than 45 seconds. Continuing to wait...
06:20:39 [try-o-rama] debug: restarted timer
06:20:39 [try-o-rama: try-o-rama conductor combined] debug: -> {
  Err: {
    Internal: '{"kind":"Timeout","file":"crates/core/src/nucleus/ribosome/runtime.rs","line":"220"}'
  }
}
```
because what I want to do is if the entry doesnt exist then commit it like
```
if hdk::get_entry(&root_anchor_entry_address)?.is_none() {
       let root_anchor_address = hdk::commit_entry(&root_anchor_entry)?;
```

**Comment by willemolding** [comment]
Hy @philipbeadle do you remember which networking implementation you were testing against? (e.g. sim1h, sim2h, memory)

**Comment by willemolding** [comment]
Ok I can confirm that if you run the sim1h tests without first starting the dynamodb instance it blocks for a minute or so and them times out.

This is really not ideal behavior. Ideally it should return an error immediately like a `network not available` error. This could allow UI to update if the network connection is lost rather than blocking

**Comment by philipbeadle** [comment]
I was using a single Conductor and memory.

**Comment by philipbeadle** [comment]
https://github.com/holochain/anchors
Tests time out when trying to get an entry that doesnt exist yet.

**Comment by willemolding** [comment]
@philipbeadle try running the tests with the Sim2h backend and see what you get. Make sure you also run a local Sim2h server on port 9000

Just run 'sim2h_server' from a nix shell in the core repo

**Comment by philipbeadle** [comment]
Works great on develop branch now :)
