### ISSUE TITLE
add code coverage into CI

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#19]
As a Holochain Core team we need to know how much of our code has tests written for it.

In the go implementation we had a code coverage that ran to check our testing.  We need to:

- [ ] find a fust code coverage tool for our CI
- [ ] add it to travis
- [ ] decide on code coverage % targets

**Comment by thedavidmeister** [comment]
@zippy the circle tutorial for rust has a section on codecov https://abronan.com/building-a-rust-project-on-circleci/

**Comment by thedavidmeister** [comment]
looks like mac os x support is missing or patchy for rust code coverage tools

i'll keep looking into travis, but #17 might be a dependency for easy local coverage checking

**Comment by thedavidmeister** [comment]
@philipbeadle ^^ FYI

**Comment by thedavidmeister** [comment]
for now i'm just making a simple docker to test out codecov options

**Comment by thedavidmeister** [comment]
followup for an alpine version #41
