### ISSUE TITLE
standard `ActionResponse` trait

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#196]
while `Action` is global, `ActionResponse` is specific to the thing responding to the action, e.g. agent/nucleus

however, a standard trait for each `ActionResponse` implementation probably makes sense

**Comment by lucksus** [comment]
I don't think we should have `ActionResponses` in general. Actions are changing the State and we now have futures polling the state to check for the anticipated outcome. Having explicit action responses other than portion of the State that gets changed by the action was an early (anti-) pattern which is not needed anymore.

**Comment by lucksus** [comment]
We do need this and I've implemented it in #1920.
