### ISSUE TITLE
should reduce_zfr store state using function call or action as key?

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#198]
both have an ID, elsewhere we use the action, what is the benefit of using the function call as the key for the state change here?

**Comment by lucksus** [comment]
My thoughts are: it is representing the domain logic in a clearer way to have the zome function call be the key. Also there is no action map in `NucleusState` which I think was a temporary solution anyways. So I want to answer this question with: the key should be the zome function call as it is right now.

**Comment by thedavidmeister** [comment]
@lucksus ok cool
