### ISSUE TITLE
acorn-hc hits a conductor panic, based on link_eavs.len()

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#2069]
https://github.com/holochain/holochain-rust/blob/45e3d89aa179c17105b91de8c72c175cbd512610/crates/core/src/nucleus/actions/get_entry.rs#L86-L90

we are running v0.0.42-alpha5. The Conductor of the second node to activate panics when we connect two nodes to a sim2h_server

<img width="570" alt="Screen Shot 2020-01-16 at 11 29 41 AM" src="https://user-images.githubusercontent.com/1409121/72558597-de3be980-3857-11ea-8afa-d86e97c8f074.png">

**Comment by Connoropolous** [comment]
Here is a new dump of the log with the full backtrace, and the full log from launch.

https://gist.github.com/Connoropolous/16f27cb573330ce47ab9b9e197ddc929

**Comment by zippy** [comment]
I think this has been fixed now no?

**Comment by Connoropolous** [comment]
yeah no longer an issue
