### ISSUE TITLE
solve the logging problem

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#21]
As Holochain core dev, I want to be able to log from different parts of the application and enable them variably.

- [ ] decide on standards for using log crate `target` variable for different contexts
- [ ] implement a complex logger that can handle a complex target for multi-coloring for the use case of hcdev using that standard

**Comment by zippy** [comment]
Note: The `log crate` is good for a global application executable log, i.e. for the container.  We should use it in all of our code for doing debugging logging so we can see what's happening in different parts of the code.  This is separate from application logging which we have to implement separately because in a given container, each application may have different logging requirements and destinations which is not a global application logging, kind of like how in Apache you configure different logs per virtual host.

**Comment by jamesray1** [comment]
@zippy is this issue still an issue? Seems like logging is available.
