### ISSUE TITLE
add Wasm global constant handling

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#218]

**Comment by zippy** [comment]
https://developer.holochain.org/API#System_globals_and_constants

**Comment by lucksus** [comment]
The link is broken.
https://developer.holochain.org even does not work.

**Comment by Connoropolous** [comment]
that's because Decko is constantly breaking and failing us

**Comment by zippy** [comment]
The issue is the current installation is not done correctly and keeps sucking up disk space.  Mamading has been working on installing it on a new box, but hasn't completed that.  Tonight I just resized the virtual server to 3 times as big so it should give us some breathing room till mamading finishes the new install.

**Comment by lucksus** [comment]
Ok, I can see the linked doc now. what exactly is this ticket about? adding all those constants to the ribosome and HDK? Exactly as it is in Go or are there changes needed?

**Comment by ddd-mtl** [comment]
Setting up the code structure for passing the globals to the wasm zome code. Implement the obvious ones and the most crucial ones,  from the Go version (not all).
