### ISSUE TITLE
404 not found https://github.com/holochain/holonix/archive/release-0.0.85.tar.gz

### ISSUE THREAD

**Issue by rohanshukla94** [holochain/holochain-rust#2211]
Hi guys so I am following this guide for windows
https://redux.developer.holochain.org/docs/install/

and running this command as mentioned

`nix-shell https://github.com/holochain/holonix/archive/release-0.0.85.tar.gz`

but I am getting this error. I am using WSL2 and Ubuntu 20.04. Thank you.

error: unable to download 'https://github.com/holochain/holonix/archive/release-0.0.85.tar.gz': HTTP error 404

**Comment by davidbios** [comment]
> Hi guys so I am following this guide for windows
> https://redux.developer.holochain.org/docs/install/
> 
> and running this command as mentioned
> 
> `nix-shell https://github.com/holochain/holonix/archive/release-0.0.85.tar.gz`
> 
> but I am getting this error. I am using WSL2 and Ubuntu 20.04. Thank you.
> 
> error: unable to download 'https://github.com/holochain/holonix/archive/release-0.0.85.tar.gz': HTTP error 404

I have same your problem
