### ISSUE TITLE
build source chain in memory on top of something with structural sharing

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#23]
current implementation involves lots of cloning of data, rather than having newer pairs simply reference older pairs and be immutable

https://docs.rs/im/10.2.0/im/ looks like something we might want here

**Comment by jamesray1** [comment]
Good suggestion, seems like it is still relevant. Given that it is an optimization, I suppose it would not become a priority until after 1.0. Perhaps we could add a label or milestone to indicate this, and similarly manage other issues? One benefit is that better issue management would help for onboarding new developers. paritytech has good examples of this, e.g. [these labels](**https://github.com/paritytech/parity-ethereum/labels**).

**Comment by jamesray1** [comment]
OTOH, it would (probably?) be easier to implement this kind of change sooner rather than later, and will then make it a less pressing need to optimize with more tailored data structures.

**Comment by thedavidmeister** [comment]
there is a discussion around structural sharing for the redux state and how locking can be done better for accessing the CAS/EAV storage (which is effectively what this refers to in more up to date terms)

https://github.com/holochain/holochain-rust/pull/1797

this popped up in chat today and is under active development as it aims to help resolve some deadlocks that we've been seeing in stress tests

![image](https://user-images.githubusercontent.com/629710/68745848-87dddf00-064b-11ea-8b14-b5c86f5f8349.png)

**Comment by thedavidmeister** [comment]
soz, that is unreadable:

> I think the real solution is to have the state be an immutable data structure with structural sharing that we don't put into a lock at all and only lock the underlying CAS inside the getters/setters of that structurally shared front-end.

**Comment by thedavidmeister** [comment]
labels can totally be a thing, but i think it makes sense to do more of that as more people are getting involved (which will be easier as we triage the issues to make that more attractive)
