### ISSUE TITLE
`docker/run` when run as root changes ownership of certain cargo folders

### ISSUE THREAD

**Issue by timotree3** [holochain/holochain-rust#236]
What I did:
- Run `. docker/run-fmt`
- Remember that my docker daemon needs to be run as root
- Run `bash -c '. docker/run-fmt'

What happened:
- Some source files were reformatted
- The next time I used `cargo` it gave me an error because my `$HOME/.cargo/registry` folder was now owned by `root`

What I expected:
- Some source files to be reformatted
- The docker scripts to change those files as my user to avoid accidental damage.

The way I see it, there are two solutions to this:
- Require that users add themselves to the system group called `docker` that lets them use this command without root
- Add a `build-arg` to the scripts that automatically detects this and changes the user in the `Dockerfile` to have the same UID as the user running the script

I would be happy to do a PR for the latter as I [have](https://github.com/holochain/holochain-proto/commit/5a6daf2376008db6eaa82417249e85573cdf333d#diff-c0d65d2fb9fff450085d1f1a44ca5bb1) [experience](https://github.com/holochain/holochain-proto/commit/5a6daf2376008db6eaa82417249e85573cdf333d#diff-ebacf6f6ae4ee68078bb16454b23247dR9) with implementing this particular feature.

edit: I was making some false assumptions about how the docker code works. After doing some more research it seems to me that the solution would be to add something that conditionally runs `sudo` like we did in holochain-proto.

**Comment by timotree3** [comment]
I just realized that there is something here in the code already that deals with `HOST_UID`s. Oops! It's still weird that I ran into the issue though.

**Comment by willemolding** [comment]
I think we have removed Docker and replaced it with nix-shell so this should no longer be an issue
