### ISSUE TITLE
readme should link to hosted mdbook

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#244]
@Connoropolous FYI

**Comment by Connoropolous** [comment]
Right you are @pdaoust I will close it. If i had of used better labeling in the PR, it would have closed it automatically. (had I said "closes #244")

**Comment by Connoropolous** [comment]
p.s. @pdaoust there is a handy label in active use, if you haven't seen it, called documentation where you can see all open issues: https://github.com/holochain/holochain-rust/labels/documentation
