### ISSUE TITLE
DHT module

### ISSUE THREAD

**Issue by lucksus** [holochain/holochain-rust#251]
We need an entity (module) that handles get_entry actions (has reducer for those) and looks in the chain and local HT and would trigger a network get if entry is not present locally.

Does not do the network stuff yet, only mocks it.

**Comment by thedavidmeister** [comment]
i haven't forgotten this, just been deep in PR land, both reviewing and polishing

**Comment by lucksus** [comment]
Correction:
We need this D mock so `invoke_get_entry()` can query that D mock **before** creating a GetEntry action.

**Comment by thedavidmeister** [comment]
mmmm
