### ISSUE TITLE
Article: How to Create A Development Kit (HDK) for a WASM-able language

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#263]
Needs to include something like what Nico was writing about in the README of hdk-rust

"Holochain apps' zome functions and validation code are represented as WASM binaries. In order to provide convenient access to the Holochain API functions and callbacks without forcing app developers to deal with pointers and de-/serialization of parameters, we provide HDK libraries that provide bindings for several source languages such as Rust and TypeScript."

Except that it is targeted at those people who want to understand the Holochain/WASM interface, so that they can write a new language Development Kit. Will be useful to our internal team, and externals

This goes under "Extending the Holochain Platform" section

**Comment by ddd-mtl** [comment]
Note: We also used the word 'toolchain' for describing the set of 'components' needed for writing an hApp in a specific language.
