### ISSUE TITLE
clippy problem in travis

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#27]
There are some kinds of weirdnesses with clippy in travis.  The first time it ran on the a branch it complained with an error like `no such subcommand: clippy`  This was fixed by adding 

`  - cargo +nightly install clippy`

Into the install section of the .travis.yml file.  But then on next push it would fail the travis run with this error:

```
cargo +nightly install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing clippy v0.0.209
error: binary `cargo-clippy` already exists in destination as part of `clippy v0.0.209`
binary `clippy-driver` already exists in destination as part of `clippy v0.0.209`
```

Furthermore clippy was being too conservative and requiring  Boxing an Enum that we don't want to box right now, so I didn't want it to fail the tests just because of that.

**Comment by thedavidmeister** [comment]
@zippy you can tweak the lints inline like this:

```rust
#[derive(Clone, Debug, PartialEq)]
#[allow(large_enum_variant)] // <--- overrides the clippy linter for this rule
pub enum Action {
    Agent(::agent::Action),
    Network(::network::Action),
    Nucleus(::nucleus::Action),
}
```

no need to nuke the whole linter :)

i got a WIP PR up to reinstate this, and also testing out the `--force` flag to try and tackle that other bug on travis you mentioned

**Comment by thedavidmeister** [comment]
aight, PR is ready to review, looks like we already had some extra warnings starting to sneak in...
