### ISSUE TITLE
tests to show that entry/header/pair are immutable

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#32]

**Comment by thedavidmeister** [comment]
@sphinxc0re is this actually possible?

i was expecting to use a `should_panic` but the private field errors are compile time, not panics

**Comment by sphinxc0re** [comment]
There are no private fields or methods in tests. All tests can access everything

**Comment by sphinxc0re** [comment]
Okay, then I don't get the question.

**Comment by thedavidmeister** [comment]
this issue is to write a test that shows that Entry cannot be accidentally modified, i.e. the fields are private

there are private fields in tests, just not in sub modules, so we could test Entry as long as we put the test outside Entry

the issue i'm facing is that private fields are compile time errors, not panics, so `should_panic` doesn't cut it here

**Comment by sphinxc0re** [comment]
You can't test for that. Rust ensures, that all private fields are immutable from the outside. So you just want to ensure that nobody is changing the visibility?

**Comment by thedavidmeister** [comment]
yes, that i what i want, but understand it isn't possible
