### ISSUE TITLE
triage clippy config

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#320]
clippy needs help if it is going to be useful

- MUST fail builds
- immediate: deny everything that is not currently failing
- immediate: warn everything that is currently failing
- immediate: warn current allow
- followup: audit each warn rule through trello decision making

**Comment by AshantiMutinta** [comment]
I just did a run on the current branch and I think a lot of it is due to unneeded return statements and moving variables that are not consumed
