### ISSUE TITLE
general utility function for building pairs from entries and previous pairs

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#34]
the golang version had things like `addEntry` and `prepareHeader` that sort-of built up pairs (there were no explicit pairs in go)

`source_chain::memory::tests` has a helper fn `test_pair` that does something like what we might want here

**Comment by jamesray1** [comment]
It looks like addressing https://github.com/holochain/holochain-rust/issues/946 would also address this?

**Comment by thedavidmeister** [comment]
yes in a broad sense, in a specific sense we don't have "pairs" any more because the terminology was confusing people (although it resurrected at some point as `EntryWithHeader`)
