### ISSUE TITLE
testing utilities

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#39]
as a core dev I want access to testing utilities that help me set up things like DNA, holochain instances etc.

- [ ] investigate solutions eg (https://stackoverflow.com/questions/41700543/can-we-share-test-utilites-between-crates)
- [ ] chose one
- [ ] fix use of test_utils crate in hc_core

**Comment by thedavidmeister** [comment]
mmmhmmm so much more can be done with testing to make it less manual

**Comment by sphinxc0re** [comment]
This property testing library looks really promising
https://crates.io/crates/proptest

**Comment by jamesray1** [comment]
Would you say this issue can be closed or still needs work? Seems to be like it it outdated and can be closed.

test-utils is used as a dev-dependency in every cargo.toml result here:

https://github.com/holochain/holochain-rust/search?q=test_utils&unscoped_q=test_utils

**Comment by thedavidmeister** [comment]
yeah, it is there.. we never got around to property testing but that could be brought up separately
