### ISSUE TITLE
use path safety logic from HashTable in FileStorage for CAS

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#399]
currently `FileTable::new()` does some safety checks on path that `FileStorage` does not do

these checks should be moved to `FileStorage` or shared by both

**Comment by jamesray1** [comment]
I'll have a go at working on this.

**Comment by jamesray1** [comment]
Is this issue up-to-date?

![image](https://user-images.githubusercontent.com/16969914/66176220-4c411400-e6a0-11e9-8de9-d4f4186eb797.png)

**Comment by thedavidmeister** [comment]
potentially not, this was created about a year ago, maybe we just close it out :)
