### ISSUE TITLE
seen in travis: test tests::can_call_commit ... ERROR: hc_commit_entry() FAILED: Validation callback not implemented for "testEntryType"

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#402]
see:

https://travis-ci.org/holochain/holochain-rust/jobs/435280342#L497

**Comment by ddd-mtl** [comment]
Its not a bug, its a feature... :)
Having this error means `hc_commit_entry()` has been correctly called.

**Comment by thedavidmeister** [comment]
@ddd-mtl oh lol, so the test is checking for the error?

**Comment by ddd-mtl** [comment]
@thedavidmeister The test is checking that we are not getting a HolochainError when calling hc_commit().
It doesn't care if the call actually succeeded or if we get a RibosomeError.
