### ISSUE TITLE
get base dockers on docker hub to DRY up the dockerfiles and speed up builds

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#46]

**Comment by thedavidmeister** [comment]
@philipbeadle suggested re-using the old travis setup as much as possible:

https://github.com/holochain/holochain-proto/blob/develop/.travis.yml#L21

**Comment by thedavidmeister** [comment]
i need someone to add encrypted docker credentials as per https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry

**Comment by philipbeadle** [comment]
Done, see #53
