### ISSUE TITLE
hdk-assemblyscript version of the memory bug

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#469]
There is a branch on hdk-assemblyscript with the code that will throw this error
https://github.com/holochain/hdk-assemblyscript/compare/memory-bug-maybe

just...
```
cd examples/appSpec
hc test
```

<img width="1680" alt="screen shot 2018-10-11 at 11 03 06 pm" src="https://user-images.githubusercontent.com/1409121/46845577-006bcf80-cdaa-11e8-830f-23c095d4ea80.png">

**Comment by AshantiMutinta** [comment]
This looks like someone is unwrapping an option. Have you checked for any "expect" in the code?

**Comment by Connoropolous** [comment]
Well, the error crops up from the Get action... but I know that @thedavidmeister and @zippy were working on that last night and are going to get back to it. I think its the memory issue they were dealing with
https://github.com/holochain/holochain-rust/blob/cc89528ac51c304e9c1a089007f4a6d64a7e4edb/core/src/nucleus/ribosome/api/get_entry.rs#L64

**Comment by AshantiMutinta** [comment]
Okay! Awesome.

Not sure if is per design but if this is happening, we should probably handle that option as well. expects and unwraps will panic the threads and stop them from executing.

**Comment by Connoropolous** [comment]
after we made some updates to hdk-assemblyscript, this went away
