### ISSUE TITLE
use collection that allows more efficient get() in source chain

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#50]
current get implementation is slow as it iterates through the whole chain with a `filter` to implement `get`.

similar to #35 this is simply due to running everything through a single vector and could be improved by leveraging additional data structures internally

**Comment by sphinxc0re** [comment]
There is `BTreeMap` and also `HashMap`. Are you suggesting one of those?

**Comment by thedavidmeister** [comment]
@sphinxc0re yes, see the related issues for further discussion

should be able to just have a hash map of pairs based on a custom hashing algo that exposes the header hash as keys + a single top pair

iterator can be built from this to have an index pair

**Comment by jamesray1** [comment]
[F7-optimization]

**Comment by thedavidmeister** [comment]
chains are now implemented by whatever persistence backend is configured in the conductor

speed optimisations (e.g. indexing) are up to whatever the storage mechanism can do
