### ISSUE TITLE
change core_api_c_bindings so `get_context` creates the file dirs if they don't exist

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#513]
Here...

cas_path and storage_path need to be created if they don't exist, otherwise the `.unwrap()` throws a panic

https://github.com/holochain/holochain-rust/blob/ed5a99c89f7985831b9f6fecca95005b015c57f4/core_api_c_binding/src/lib.rs#L51-L70

**Comment by AshantiMutinta** [comment]
#515 done here.

**Comment by lucksus** [comment]
Ah, I should have maybe commented here.
I don't think we can get around passing in a path from the container since we actually need a `Holochain::load()` function. HoloSqape and hcshell already manage a setting directory that also gets created if not existent.

**Comment by Connoropolous** [comment]
New issue at #518
