### ISSUE TITLE
Persist Agent State

### ISSUE THREAD

**Issue by AshantiMutinta** [holochain/holochain-rust#520]
At the moment, the only state we are saving is an agent state. We need to go further and allow the add and retrieval of the state

**Comment by lucksus** [comment]
Does the agent state get saved? I mean, right now that is all that is needed, because we need to persist `top_chain_header`.

I think the only thing that is persisted right now is the `ChainStorage` and `DhtStorage`. `ChainStorage` < `AgentState`.

**Comment by AshantiMutinta** [comment]
Oh that is much easier. I will change issue to reflect that as top_chain_header is not persisted
