### ISSUE TITLE
Riker Actors - use in CAS and NET (discussion placeholder)

### ISSUE THREAD

**Issue by neonphog** [holochain/holochain-rust#574]
Alright, I closed https://github.com/holochain/holochain-rust/pull/572 because it was ill-conceived. wasm-test builds break when we bring riker into core_types.

@zippy @lucksus @thedavidmeister 

But there was some discussion that should be continued. That can continue here.

@thedavidmeister and I discussed, and decided that the least disruptive way forward would be to use a separate riker ActorSystem and Protocol for `net` and `net_ipc`. ActorSystems have a lot of overhead in terms of thread pools and schedulers, and actors within each separate system cannot talk to each other. We should keep an eye out for this pattern repeating itself... we may need to consolidate ActorSystems at some point.

@lucksus says:

> Is there a way to not use Riker for net? We will want to compile Holochain to WASM for Holo soon. Putting Riker into net which we need in core makes that impossible, currently. @neonphog

Two points in response:

### 1

We will need hooks into the CAS system in the WASM build for Holo as well, so we'll either need to figure out how to get riker built for both CAS and NET, or we'll need to abstract the the access points at both the CAS module and the NET module, right? (also, the net module for Holo will be almost entirely a shim that communicates through the webproxy system using the net module of the session host)

### 2

https://hackmd.io/_OIEfnTOSzWtW_7sUw6lrg had a couple assumptions of synchronous data retrieval that would have either ballooned the callbacks, or required busy waiting on the thread.

Even just in testing I found the callbacks hard to deal with, when what we really want, for the most part, is to be notified of events from the other end, which is exactly what riker provides.

---

I'm totally up for feedback on the above points, or other suggestions for frameworks to mitigate the issues I ran into, but I think switching to riker would greatly simplify the net api abstraction.

**Comment by neonphog** [comment]
a'ight. I think I've come up with a light-weight interface that address the issues I ran into (and will compose between the network abstraction and the ipc abstraction) without using riker, but that will easily slot into riker should we choose to move that direction.

I'll post some more details as I nail down the usage.

You can track my WIP if interested: https://github.com/holochain/holochain-rust/compare/net-connector

**Comment by thedavidmeister** [comment]
IIRC the issue with compiling riker was some upstream dependency issue

i'm disappointed that we would make key architectural decisions based on a couple of upstream semver bumps (or lack of)

what have we done so far to try and move the upstream repos forward?

is there another reason that riker poses a problem?

**Comment by thedavidmeister** [comment]
also nice work on finding an alternative approach

**Comment by neonphog** [comment]
closing now that https://github.com/holochain/holochain-rust/pull/621 and friends are merged
