### ISSUE TITLE
HDK get_links and load

### ISSUE THREAD

**Issue by willemolding** [holochain/holochain-rust#579]
Loading all the entries that are linked to a particular address is a very common pattern. 

In proto there was the option to specify if the linked entries should be loaded as well using `getLinks(base, tag, {Load: true}) `. 

It would be nice to have something like this in the new HDK. The functionality is added by this function which could be included in the HDK directly or its functionality added to get_links instead. 

```rust
struct GetLinksLoadElement<T> {
	address: HashString,
	entry: T
}

type GetLinksLoadResult<T> = Vec<GetLinksLoadElement<T>>;

fn get_links_and_load<T, S: Into<String>>(
    base: &HashString, 
    tag: S
) -> ZomeApiResult<GetLinksLoadResult<T>> where T: DeserializeOwned {
	hdk::get_links(base, tag)
		.map(|result| {
			result.links.iter()
				.map(|address| {
					hdk::get_entry(address.to_owned())
						.map(|entry: Option<T>| {
							GetLinksLoadElement{
								address: address.to_owned(),
								entry: entry.unwrap()
							}
						})
						.ok()
				})
				.filter_map(|elem| elem)
				.collect()
		})
}
```

**Comment by Connoropolous** [comment]
Totally agree.

**Comment by philipbeadle** [comment]
Great, because at the moment we are wrapping our struct in another one to have the address in the returned list of results and its too verbose :)

**Comment by willemolding** [comment]
This is implemented in the utils crate
