### ISSUE TITLE
helpers to map some sequence of content to pairs

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#62]
source chain tests could be much neater with a little destructuring:

```rust
        let p1 = test_pair(None, "foo");
        let p2 = test_pair(Some(&p1), "bar");
        let p3 = test_pair(Some(&p2), "baz");
```

could be more like:

```rust
    let (p1, p2, p3) = test_pairs(["foo", "bar", "baz"]);
```

**Comment by jonathan-s** [comment]
@thedavidmeister It seems like this issue is no longer relevant. I can't find the code that you mentioned. `source_chain` seems to have been transformed into `chain_store`?

**Comment by thedavidmeister** [comment]
@jonathan-s thanks for auditing that :)
