### ISSUE TITLE
review whether it still makes sense to panic in source chain pushing once we have more sophisticated validation

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#63]
currently validation is _only_ based on hashes - pushing invalid hashes onto a source chain is a panicable offense, because hashes should never fail to line up at that point, that's _always_ a bug in core.

however, once validation can be farmed out to zomes, this may no longer be the case so we should return `Result` instead.

**Comment by thedavidmeister** [comment]
@sphinxc0re FYI ^^

**Comment by jamesray1** [comment]
It seems like validation can now be pushed out to zomes, as shown e.g. here:

https://github.com/holochain/holochain-rust/blob/fb13b213a1b3c5c15814aa00435c71428dbbf7d2/doc/holochain_101/src/zome/entry_validation.md

And it seems like validation functions now return a `ValidationResult` e.g. as shown here:

`pub fn validate_provenances(validation_data: &ValidationData) -> ValidationResult {`
https://github.com/holochain/holochain-rust/blob/aa53657ee25bd35304c177a8d5560318644b0ccf/crates/core/src/nucleus/validation/provenances.rs

Is this out of date?

[M4-core][Z3-stale]

**Comment by thedavidmeister** [comment]
@jamesray1 yeah validation has been rewritten several times since this was opened, thanks
