### ISSUE TITLE
add malloc to wasm

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#65]
Currently the returned serialized parameter from a function call overwrites the input parameters (which is probably ok), but if the return value were longer than one page of memory this would be a problem.

- [ ] add malloc so we can increase page size
- [ ] use malloc in the serialization of the output params

**Comment by lucksus** [comment]
This is not too complex and we can look at how paritytech did it for polkadot: https://github.com/paritytech/polkadot/blob/master/substrate/executor/src/wasm_executor.rs

see the ```struct Heap``` and how it is used in ```ext_malloc()```.

**Comment by ddd-mtl** [comment]
@lucksus Should I implement this for the Commit API function?

**Comment by zippy** [comment]
We are probably going to need it anyways... I know that parity folks
already implemented a version of it for their wasm stuff so we can probably
grab use what they've done.  Pretty sure @lucksus knows where it is in
their code.
