### ISSUE TITLE
Trying to link an Entry to hdk::DNA_HASH

### ISSUE THREAD

**Issue by akritrime** [holochain/holochain-rust#651]
**Edit**: This is for the master branch of the API. I just realized that the development branch has a special data type called Entry. However I am not talking about that one, entry here represents a generic object that we want to store on the DHT.

Code: 
```
fn handle_create_entry(entry: Entry) -> serde_json::Value {
    let dna_hash = &HashString::from(hdk::DNA_HASH.to_string());
    

    match hdk::commit_entry("entry", json!(entry)) {
        Ok(address) => {
            let link_result = hdk::link_entries(
                dna_hash,
                &address,
                "entry_data"
            );
            if link_result.is_err() {
                return json!({
                    "success": false,
                    "error": link_result.err().unwrap()
                })
            }
            
            json!({"success": true, "address": address})
        },
        Err(hdk_err) => json!({"success": false, "error": hdk_err}),
    }
}
```

# What am I trying to do?

I want to make these particular entries available across all the nodes in the app so that anyone can query and get a list of these entries. Currently, the best solution for this seems to be linking to a hash that will be available in all the instances. However, when I try to run this in the tests, I get an error. 
```
{"Internal":"ErrorGeneric(\"Base for link not found\")"}
```

I am new to Holochain, so it could be quite possible that I am missing something simple. Any help on how to solve this would be appreciated.

**Comment by willemolding** [comment]
Linking to the DNA hash is not possible as the DNA entry itself doen't live on the DHT (only on every agents local chain). There are many other possible ways to have a base that is accessible to all agents. I suggest you take a look at the anchor pattern (see how it is used in [this example](https://developer.holochain.org/guide/latest/first_steps.html))
