### ISSUE TITLE
merge all hash references into a single header property

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#68]
discussed with @zippy this morning

we currently have three hash references in the header:

- previous header
- entry for this header
- previous header with the same type

and entries do their own hash referencing, e.g. with links

would it make sense to have a single property in the header `links` or `refs` that covers all of this?

**Comment by zippy** [comment]
I think we should do this as an implementation detail, but I do not think we should expose the ability to add link types to the application developer yet.  Let's wait until there's an actual use case that requires it.

**Comment by artbrock** [comment]
Yeah... we can do this as a generalized structure that could be extended later, but if the intention is to be able to do better linking DAG-style, I don't think this will give us that. Each header becomes immutable as soon as the next header is written, this would mean that future things could link to past things, but you could never put links on past things to future things, so it isn't very expressive.

I think what we're really looking for is that these are stored in a KV store with better indexing, searching, querying for rapid local search and look-ups. So we should find a nice Rust-based persistor which gets us that.

**Comment by thedavidmeister** [comment]
@artbrock mhmm, good point about losing extensibility after the initial hashing

the querying stuff is on the cards for sure as we evolve the relevant traits :)

**Comment by jamesray1** [comment]
[F7-optimization][P7-nicetohave]

**Comment by thedavidmeister** [comment]
ship has probably sailed on this one

changing the structure of headers would introduce more churn that can be justified purely by aesthetics
