### ISSUE TITLE
`hc --version` not working: showing libzmq library not found

### ISSUE THREAD

**Issue by bboyatwork** [holochain/holochain-rust#701]
After completing installation steps 1 through 4 listed here: https://developer.holochain.org/start.html ... I get the following error when trying to do step 5 in checking the hc version
```
Micahs-MacBook-Pro:~ alchemicalu$ hc --version
dyld: Library not loaded: /usr/local/opt/zeromq/lib/libzmq.5.dylib
  Referenced from: /Users/alchemicalu/hc/hc
  Reason: image not found
Abort trap: 6
```

**Comment by zippy** [comment]
I guess we need to add the zmq install dependency as detailed in the [README](https://github.com/holochain/holochain-rust/blob/develop/cmd/README.md) into those instructions, @Connoropolous?

**Comment by bboyatwork** [comment]
Thanks @zippy - after installing that it worked just fine 👍 so yea adding that to the installation instructions would help.

**Comment by marcusnewton1** [comment]
@Connoropolous Sorry, what are we supposed to do with the downloaded ZMQ library on windows?

**Comment by marcusnewton1** [comment]
in the `lib` folder in the nightly toolchain?

**Comment by marcusnewton1** [comment]
@Connoropolous Might be worth mentioning to windows users something like "We'll deal with the downloaded ZMQ library in step five", I got confused what I was supposed to do with it

**Comment by koalyptus** [comment]
as per @marcusnewton1 comment, for windows users worth mentioning in step 4 what to do with the dll file. 
Cheers

**Comment by BeneeictGIT** [comment]
Hello there, is there any thing that i can do for the ZMQ cause the link provided doesn't go through. I am not a programmer as well. thanks 
Video is better for the people dont know programming. I just want the help the HOLO community.

**Comment by thedavidmeister** [comment]
a few things:

- there is a `build.rs` file in develop that copies the zmq dep into place (the `.cargo` dir which is assumed to be on your path if the `cargo` command works) for windows, running `cargo build` in the root should trigger this, it only needs to happen once
- installing zmq on other platforms can be done automatically with the install script documented in the README
- zmq is going away soon https://github.com/holochain/holochain-rust/pull/1055

i'm going to close this

@ me if you need it re-opened, thanks :)
