### ISSUE TITLE
Nodejs container for tests failing for 64-bit windows

### ISSUE THREAD

**Issue by marcusnewton1** [holochain/holochain-rust#712]
Error log: https://pastebin.com/2TgPhiRK

edit: added context to log output

**Comment by Connoropolous** [comment]
Hi @marcusnewton1 , I see this in the error message... 
"C:\PATHTOHAPP\..."
Is that a real directory on your computer? Can you try to find where that string comes from?

That may give us some insight on this problem. I am not running on windows myself

**Comment by ddw360** [comment]
@marcusnewton1 @Connoropolous 
Was able to get this to work. See pastebin link (https://pastebin.com/GkqTm16Q).
Fix was to make sure "hc.exe" and "libzmq-v140-mt-4_*.dll" directory was in command environment path instead of using absolute reference.

**Comment by marcusnewton1** [comment]
@Connoropolous no that was just me obscuring the path for personal reasons.

Good to hear @ddw360.

**Comment by Connoropolous** [comment]
Excellent! Can this be closed?

**Comment by marcusnewton1** [comment]
I'm very new to issue etiquette, just wanted to report a bug. Happy to close it, my assumption was to keep this issue open until a pull request is created.
