### ISSUE TITLE
is it possible to test that type_next changes the hash of a Header in an isolated way?

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#76]

**Comment by jamesray1** [comment]
[F4-tests][P5-sometimesoon]

**Comment by jamesray1** [comment]
Glancing at https://github.com/holochain/holochain-rust/blob/aa53657ee25bd35304c177a8d5560318644b0ccf/crates/core_types/src/chain_header.rs#L387-L403 it looks like this may have been tested/implemented?

**Comment by thedavidmeister** [comment]
@jamesray1 indeed that test looks like exactly what is described here :+1:
