### ISSUE TITLE
don't serialize entry_type into Entry (it should only be in Header)

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#80]

**Comment by jamesray1** [comment]
[M4-core][F7-footprint]

This seems fairly straightforward to implement. I'm willing to work on this.

**Comment by thedavidmeister** [comment]
@jamesray1 the way that entries are represented has changed since this was opened

this is what it looks like now

```
pub enum Entry {
    #[serde(serialize_with = "serialize_app_entry")]
    #[serde(deserialize_with = "deserialize_app_entry")]
    App(AppEntryType, AppEntryValue),

    Dna(Box<Dna>),
    AgentId(AgentId),
    Deletion(DeletionEntry),
    LinkAdd(LinkData),
    LinkRemove((LinkData, Vec<Address>)),
    LinkList(LinkList),
    ChainHeader(ChainHeader),
    ChainMigrate(ChainMigrate),
    CapTokenClaim(CapTokenClaim),
    CapTokenGrant(CapTokenGrant),
}
```

the enum variants themselves are serialized and this is a good thing because it allows us to automatically be strict about various things (e.g. using `match` to have the compiler force us to exhaust system/app entry types) and to easily serialize/deserialize more safely

for background, `Entry` used to be a struct not an enum, so in that context the type was just cruft

**Comment by jamesray1** [comment]
Ah okay, I did see the above code, but the explanation makes sense.
