### ISSUE TITLE
hdk::AGENT_ADDRESS does not seem to be a hashstring.

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#866]
I'm using the new Holochain-Rust 0.0.3 now, if I use hdk::AGENT_ADDRESS in my Zome method, calling from the test container in index.js, the value to_string() is "alice-----------------------------------------------------------------------------AAAIuDJb4M".

It should be "Qm..." shouldn't it? I don't even think I'm doing anything but printing the value that the HDK is giving me.

**Comment by zippy** [comment]
agent addresses won't be b58 encoded, they are

**Comment by neonphog** [comment]
@pythagorean - thanks for checking in! As @zippy mentions, we're taking a shortcut with the agent identifiers, using them directly so that we'll be able to verify signatures, and encrypt data to a remote target without having to do a dht lookup for the actual agent entry.

The nickname and all the dashes are a stand-in until we get our crypto module included (https://github.com/holochain/holochain-rust/pull/863).

**Comment by Connoropolous** [comment]
@pythagorean what is that you were trying to achieve, when this came up? is there a way we can help give additional useful info?

**Comment by Connoropolous** [comment]
Feel free to reopen this issue (and change the title) if there's something ongoing that you want to continue to work to resolve

**Comment by pythagorean** [comment]
I was using the hdk::AGENT_ADDRESS to link with, thus (excerpted and omitting some error checking code):

  fn use_handle(handle: &str) -> ZomeApiResult<Address> {
    let handle_entry = Handle::new_entry(handle)?;
    let handle_address = hdk::entry_address(&handle_entry)?;
    hdk::commit_entry(&handle_entry)?;
    hdk::link_entries(&AGENT_ADDRESS, &handle_address, "handle")?;
    Ok(handle_address)
  }

This sends me a Qm... address as expected.

However, if I use the same &AGENT_ADDRESS (passed as parameter) to retrieve the handle, it no longer works, though it did with 0.0.2, now I get back an empty string:

  fn get_handle(address: &Address) -> ZomeApiResult<String> {
    let links = hdk::get_links(address, "handle")?;
    let addresses = links.addresses();
    if addresses.len() < 1 {
      return Ok("".into())
    }
    Ok(Handle::value(addresses[0].to_owned())?)
  }
