### ISSUE TITLE
Mock of Local side of DHT

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#88]
As a Holochain core dev I'd like to pretend to have a working DHT though I don't in order to be able to write the front-house pieces and have them working already without DHT implementation.

**Comment by thedavidmeister** [comment]
@zippy @artbrock @lucksus @ddd-mtl @sphinxc0re WIP writeup for comment/collaboration up at hackmd:

https://hackmd.io/XiIpJq2oREmkjknBDnf9Uw

**Comment by thedavidmeister** [comment]
high level summary of hackmd and discussions:

to implement a _D_HT we actually need 3 things:

- a HT
- a network
- an event driven _D_ that sits between the HT and network to co-ordinate pairs and messages respectively

so @zippy is working on the network, and i will focus on the HT

still a bit vague on what is needed for an MVP from the perspective of the "front-house pieces", but i think the other two components are much better specced now than they were a week ago :)
