### ISSUE TITLE
hdk::send() unmarshalling problem

### ISSUE THREAD

**Issue by juliolrmonteiro** [holochain/holochain-rust#892]
I added a test of `hdk::send` on **app_spec** just including the basics from the dev docs, but the test I added seems to be failing because of a JSON parsing error, there's a PR [here](https://github.com/holochain/holochain-rust/pull/891).

Thanks for the assistance!

**Comment by willemolding** [comment]
Deserializing results from send/receive can now be handled in the zome code as of #1493
