### ISSUE TITLE
hdk::get_links on &AGENT_ADDRESS before linking causes it to fail to find links made later

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#914]
I can commit an entry and then link it to the AGENT_ADDRESS and then retrieve it:

```
hdk::link_entries(&AGENT_ADDRESS, &committed_addr, "some_tag")?;
// [delay of one second or more]
let links = hdk::get_links(&AGENT_ADDRESS, "some_tag")?;
let addrs = links.addresses();
```

In this case, addrs.is_empty() will be false as it should be, and I can use addrs[0] to retrieve my entry.

However, if I perform hdk::get_links prior to hdk::commit_entry and hdk::link_entries, then even after committing, the above code will make addrs.is_empty() true.

**Comment by pythagorean** [comment]
In other words, how do I check to see if something is already linked to AGENT_ADDRESS without causing subsequent links to fail?

**Comment by pythagorean** [comment]
Okay my workaround for now, which avoids this issue, is to store an entry to represent that there is something linked to AGENT_ADDRESS, and then check if that entry exists before looking for links.

**Comment by maackle** [comment]
This seems to be an instance of the bug that was fixed by https://github.com/holochain/holochain-rust/pull/857. That PR was merged in 2 days after 0.0.3 was released, so the bug still exists in the latest release. @pythagorean, if you'd like, you could try building based on `develop` and see if the bug still persists, or wait until the next release.

**Comment by pythagorean** [comment]
Looks like the same bug, @maackle. My workaround is successful for now, and using develop might introduce more instability, so I'll stick with this until the next release I guess.

**Comment by pythagorean** [comment]
My workaround for this was inadequate for the case where a second commit and link was made, and I have switched to the `develop` branch now which has resolved both issues and my workarounds are no longer necessary.
