### ISSUE TITLE
When packaging: panicking at failed instantiation for hc_link_entries

### ISSUE THREAD

**Issue by marcusnewton1** [holochain/holochain-rust#937]
Error when running `hc package`: 
```
    Finished release [optimized] target(s) in 8.59s
thread 'main' panicked at 'Failed to instantiate module: Instantiation("Expected function with type Signature { params: [I64], return_type: Some(I64) }, but actual type is Signature { params: [I32], return_type: Some(I32) } for entry hc_link_entries")', src\libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

On `develop` branch as of 31/01/2019.

Repo [here](https://github.com/OmniProject/omni/tree/pre-0.0.4).

**Comment by maackle** [comment]
@marcusnewton1 can you try rebuilding fully with `make`? Looks like something was not rebuilt since a change introduced recently.

**Comment by marcusnewton1** [comment]
@maackle I've just been using the 0.0.3 release. I'll try deleting the .cargo checkouts and trying again with the v0.0.3 tag

**Comment by marcusnewton1** [comment]
I reinstalled everything and I just get an error related to uuid for `holochain_core_types`:

```
   Compiling holochain_core_types v0.0.3 (https://github.com/holochain/holochain-rust?tag=v0.0.3#1d93ee94)
error[E0599]: no function or associated item named `new_v4` found for type `uuid::Uuid` in the current scope
  --> C:\Users\marcu\.cargo\git\checkouts\holochain-rust-c3b6365fc5bfa642\1d93ee9\core_types\src\cas\storage.rs:87:9
   |
87 |         Uuid::new_v4()
   |         ^^^^^^^^^^^^ function or associated item not found in `uuid::Uuid`
```

**Comment by marcusnewton1** [comment]
@maackle Everything eventually compiles correctly when I:
1. set the Cargo.toml for each zome to `branch = "develop"` -> compile should fail, but `Cargo.lock` generated
2. then changing to `tag = "v0.0.3"` -> compiles without uuid error.
