### ISSUE TITLE
Holochain_Container Not Find

### ISSUE THREAD

**Issue by yavuzsyildiz** [holochain/holochain-rust#983]
When i try to install holochain_container, i got an error message which is at following line:

error: could not find `holochain_container` in https://github.com/holochain/holochain-rust.git?branch=develop

**Comment by yavuzsyildiz** [comment]
ok, i solved it. But contructor is still stated as container on Quick Start page. Please update installion instructions.

**Comment by willemolding** [comment]
The quickstart guide has been updated to reference the holochain container (now just called `holochain`)
