### ISSUE TITLE
Network Abstraction Layer

### ISSUE THREAD

**Issue by lucksus** [holochain/holochain-rust#99]
As a Core Dev I want a Networking Abstraction Layer so that I can connect HC to Promether or other net libs.

- [ ] minimal notion of a Node/Peer that can send and receive to other nodes
- [ ] minimal notion of Node Address that wraps the nodes logical (i.e. hash) & transport addresses.
- [ ] minimal notion of Node/Peer Store that allows us to resolve node logical address to transport address.

**Comment by zippy** [comment]
This can @neonphog's https://github.com/holochain/lib3h 

Also found that the libp2p folks have a rust version available too now: https://github.com/libp2p/rust-libp2p/tree/cace5bf577c53809aad514db40e72f7290e030d4 (not complete but looks pretty solid)

**Comment by neonphog** [comment]
# Transport Abstraction Feedback

## Serialization Types

### SerializedAddress

(Note after-the-fact: some clarity is added in the "new_node / from param send/deliver" section below.)

Is this meant to uniquely identify a node? If so, maybe we should call it `SerializedIdentity` or something? The following comment assumes this is the intention:

- I'd suggest using `Vec<u8>` as the type for SerializedAddress, this will allow us to gain a slight efficiency by pluging in the raw bytes of the agent's public key (not sure how dpki fits into this).
- The base58 or whatever representation we want to use would only be applied when interaction with logs or user i/o.

### SerializedMessage
- I'd suggest using `Vec<u8>` as the type for SerializedMessage, to allow the use of lower-level, more efficient message packing schemes, whether we roll our own, or use something like https://crates.io/crates/rmp

### TransportAddress
- This one is tricky, I'm tempted to say it should be a `Vec<u8>` as well and let the underlying transport define it however we want, but it also seems like we want it to be human readable for debugging issues. We could go with a url scheme, and either leave it as a String, or explicitly make it a https://crates.io/crates/url, but what of transports that may have multiple paths to reach the same node?
- Perhaps this should actually just be a `Display + PartialEq` trait object that can be defined internally by the specific transport?

## TransportAddress Needed?

See the Config and Persistence notes below, but do we actually need the TransportAddresses to be accessible from the HC code at all? There's currently no apis that take them as input, and I can't think of a strict need if the transport lib is handling the routing / p2p network.

## `new_node` / `from` param send/deliver

Ahh... I see now some differences in how we've been thinking about this.

Even if we are running multiple apps with separate distinct identities within the same "container" (or whatever we will call it) or system, I'm not sure we want to explode the p2p network with additional nodes to reflect this.

Perhaps there could be a distinction of an ephemeral "System Identity" that app identities could map to at a level above this?

Not to introduce another asumption (ahem), but if we have the ability to layer multiple DHT spaces above the current set of transports, we could dedicate one of them to identity mapping, resulting in the ability to do something like:

```
// psuedo code
func send(
    to_system: SystemId,
    message: {
        from_app: AppId,
        to_app: AppId,
        data: *
    }
)
```

Alternately, we could require transports to internally handle this mapping?

## Messaging and RPC

So far, I've been imagining the transport layer being direct-message-only, and not tracking any state for responses. I'd imagined the state tracking being at a level above, i.e. holochain could pass a message identifier in with requests, and the remote end would include that id in the response.

We just need to figure out where we want this responsibility to live. For lib3h or any other transport, we could absolutely implement that state tracking in the interface under this abstraction layer, but maybe it would make sense to standardize the implementation one layer up?

## Thoughts on Configuration

If a user is running a holochain node that is using lib3h, they'll need some configuration stored specific to the lib3h transport.

I was originally thinking it would be cool if we could merge this seamlessly into the main toml or whatever format config file that we are using for holochain itself... but I feel like that is an abstraction rabbithole that we shouldn't go down.

Instead, we could add an interface to the Transport trait:

```rust
/** return a default config with best guesses,
 * and plenty of comments for more indepth configs.
 */
fn get_default_config(&self) -> String;
```

Then add a `config: String` parameter to the `new_node()` function.

Holochain would be responsible for saving / loading the config file.

- How do we know what the extension should be?
- Should we require it to be toml / some other config format?

## Persistance

Do we want the transport to be responsible for any runtime data persistance that might be appropriate (like node connection / routing / caching info, etc). It seems like it would be nice if the transport library did NOT have any direct file access, but delegated to the holochain app for that. But it would also add a lot of complexity to the abstraction interface.

**Comment by zippy** [comment]
- Totally agree about about Vec<u8> I just did strings to get off the ground, will fix.
- I'm guessing we're gonna need the transport address for the routing layer.  haven't gotten there yet, and I want to have some conversation about this..  but am assuming it will be an opaque address, i.e. it could be something like: "132.3.2.9:3141?99" where the last bit is an id that gets you to the correct app inside the other IP container at 132.3.2.9 on port 3141 (see below).
- the new_node thing is meant to be the way you register an app ID (i.e. hash) with a transport layer and register the handler callback that gets run when messages arrive for that app.  I'm making no assumptions about whether the transport layer connects to other containers to deliver that message to the given app, or if it has a per-transport address.   But maybe this is a mistake.   I don't think we want to create a new high level abstraction of identity for containers.

**Comment by zippy** [comment]
Regarding messaging and RPC: @neonphog I'm assuming what you mean here is the way send has a callback that expects to receive a response message.   I get that this is not really a low level thing that we would want to necessary be re-implemented by every transport.  However, it seemed to me that many transports might already implement it, i.e. lets say the "transport" uses http that already includes a response, or for example libp2p which also did.  In that case we wouldn't want to re-implement the message id one layer up.   I'd suggest we create a side-crate (or should that be middlware-crate?) that transport developers can use if their transport doesn't handle this.

**Comment by neonphog** [comment]
@zippy 
> I'd suggest we create a side-crate (or should that be middlware-crate?) that transport developers can use if their transport doesn't handle this.

I like that idea. I'll assume, for now, that the response tracking will be handled in the lib3h integration with holochain, and we'll make that general enough that it can be applied to other libraries.

> it could be something like: "132.3.2.9:3141?99" where the last bit is an id that gets you to the correct app inside the other IP container at 132.3.2.9 on port 3141 ... I don't think we want to create a new high level abstraction of identity for containers.

lib3h is currently expecting an identity for each node, i.e. a public key for the system, say "123" for illustration. The p2p network will route messages using this ID, so in your opaque transport address example, that would be something like "123?abc" if "abc" was the app identity.

So, If Alice's holofuel identity is "abc", and Bob's is "def". Alice needs to send a node-to-node message to "123?def", but how does she know bob's network address is "123"? We'd need a mapping somewhere of app id's to system ids, so we know where Bob is currently running his holofuel app?

**Comment by zippy** [comment]
@neonphog is the config something that gets passed in when every node gets created?  I was actually assuming there would be a trait `fn initialize(config: String) -> Result((), Error)` or something like that that would receive the config.  But maybe each node gets one too?  Doing a WIP PR so rest of team can start reviewing as well..

**Comment by lucksus** [comment]
Protocol spec draft: ﻿﻿﻿https://hackmd.io/_OIEfnTOSzWtW_7sUw6lrg#

**Comment by lucksus** [comment]
@neonphog's Rust based example API draft: https://hackmd.io/QuFzZLO2QYuWHvNzJeq32A
